### ISSUE TITLE
Python: Bug: 404-resource-not-found error when using kernel.invoke from Azure web app

### ISSUE THREAD

**Issue by Shavivek** [microsoft/semantic-kernel#10040]
**Describe the bug**
I have a Django web app (python stack) that has few features which use Azure OAI models using semantic-kernel. My app works perfectly on local machine but when I deploy it to Azure web service, the Azure OAI capabilities fail with the error: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

**To Reproduce**
I am unable to reproduce the issue locally. My app has 2 main files:
1. To get a kernel configured.
def getKernel():

    kernel = Kernel()

    if 'WEBSITE_HOSTNAME' not in os.environ:
        config_file = "app_settings.config"
        config_object = ConfigParser()
        config_object.read(config_file)
        deployment = config_object['azureOpenAI']['AZURE_OPENAI_DEPLOYMENT_NAME']
        api_key=config_object['azureOpenAI']['AZURE_OPENAI_API_KEY']
        endpoint=config_object['azureOpenAI']['AZURE_OPENAI_ENDPOINT']

    else:
        deployment = os.environ['AZURE_OPENAI_DEPLOYMENT_NAME']
        api_key=os.environ['AZURE_OPENAI_API_KEY']
        endpoint=os.environ['AZURE_OPENAI_ENDPOINT']

    service_id = "default"
    
    kernel.add_service(AzureChatCompletion(
        deployment_name=deployment,
        api_key=api_key,
        endpoint=endpoint, # Used to point to your service
        service_id=service_id,
    ))
    return kernel

and 2 - files that call into semantic functions to get response from OpenAI models.
async def getSpendDetailsLLM(mssg):
    
    kernel = sk.getKernel()
    
    # Get entity Semantic function from the plugin directory
    getSpendDetails = kernel.add_plugin(parent_directory=plugins_directory, plugin_name="ExpensePlugin")
    getSpendDetailsFunc = getSpendDetails["SpendDetails"]

    # Get required entities from message
    spendDetails = await kernel.invoke(function=getSpendDetailsFunc, arguments=KernelArguments(mssg=mssg))
    # print (spendDetails)
    spendDetailsJson = json.loads(str(spendDetails))
    return spendDetailsJson

The statement above "await kernel.invoke" causes exception when executed from the Azure instance but works as expected when works locally.
Traceback (most recent call last):
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py", line 51, in _send_request
    response = await self.client.chat.completions.create(**request_settings.prepare_settings_dict())
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 1289, in create
    return await self._post(
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/openai/_base_client.py", line 1805, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/openai/_base_client.py", line 1503, in request
    return await self._request(
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/openai/_base_client.py", line 1599, in _request
    raise self._make_status_error_from_response(err.response) from None

The above exception (Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}) was the direct cause of the following exception:
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 178, in _invoke_internal
    chat_message_contents = await prompt_render_result.ai_service.get_chat_message_contents(
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py", line 111, in get_chat_message_contents
    return await self._send_chat_request(settings)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py", line 272, in _send_chat_request
    response = await self._send_request(request_settings=settings)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py", line 67, in _send_request
    raise ServiceResponseException(

The above exception (("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", NotFoundError("Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}"))) was the direct cause of the following exception:
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/kernel.py", line 180, in invoke
    return await function.invoke(kernel=self, arguments=arguments, metadata=metadata)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/functions/kernel_function.py", line 211, in invoke
    await stack(function_context)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 184, in _invoke_internal
    raise FunctionExecutionException(f"Error occurred while invoking function {self.name}: {exc}") from exc

The above exception (Error occurred while invoking function SpendDetails: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", NotFoundError("Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}"))) was the direct cause of the following exception:
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 170, in get
    return super().get(request, *args, **kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 135, in get
    return self.render_to_response(self.get_context_data())
  File "/tmp/8dd28badf0397ed/spend/viewClasses/smsProcessviews.py", line 295, in get_context_data
    context = super(SMSRecordCreateViewLLM, self).get_context_data(**kwargs)
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 68, in get_context_data
    kwargs['form'] = self.get_form()
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 35, in get_form
    return form_class(**self.get_form_kwargs())
  File "/tmp/8dd28badf0397ed/spend/viewClasses/smsProcessviews.py", line 385, in get_form_kwargs
    kwargs = super(SMSRecordCreateViewLLM, self).get_form_kwargs()
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 107, in get_form_kwargs
    kwargs = super().get_form_kwargs()
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/django/views/generic/edit.py", line 40, in get_form_kwargs
    'initial': self.get_initial(),
  File "/tmp/8dd28badf0397ed/spend/viewClasses/smsProcessviews.py", line 316, in get_initial
    smsDetails = asyncio.run(lu.getSpendDetailsLLM(sms))
  File "/opt/python/3.12.2/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/opt/python/3.12.2/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/opt/python/3.12.2/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
  File "/tmp/8dd28badf0397ed/azureOAI/llmExpense.py", line 112, in getSpendDetailsLLM
    spendDetails = await kernel.invoke(function=getSpendDetailsFunc, arguments=KernelArguments(mssg=msgg))
  File "/tmp/8dd28badf0397ed/antenv/lib/python3.12/site-packages/semantic_kernel/kernel.py", line 189, in invoke
    raise KernelInvokeException(

Exception Type: KernelInvokeException at /spend/sms/new/3096
Exception Value: Error occurred while invoking function: `'ExpensePlugin-SpendDetails'`

I have ensured that the env variables for API-version, Deployment-name etc. in config on local machine and on azure are same.

**Expected behavior**
The functions should behave same when executed locally or from Azure instance.

**Screenshots**

**Platform**
 - OS: Localmachine: Windows, Azure: Linux
 - IDE: VSCode
 - Language: Python 3.12 on Linux
 - Source: semantic-kernel==1.1.2

**Comment by alliscode** [comment]
Hi @Shavivek, without being able to debug the code, my best guess would be some of the environment variables are not being configured correctly...

```
deployment = os.environ['AZURE_OPENAI_DEPLOYMENT_NAME']
api_key=os.environ['AZURE_OPENAI_API_KEY']
endpoint=os.environ['AZURE_OPENAI_ENDPOINT']
```

Could you add logging to verify that these environment variables are being set as expected in your deployment?

**Comment by moonbox3** [comment]
Hi @Shavivek, is this accurate: `Source: semantic-kernel==1.1.2`? Can you please try to use our latest package version `1.17.1`? If you are indeed using `1.1.2`, that is a very old package from about May of 2024. :)

In any case, as @alliscode mentioned, adding some logging can help -- it does look like something may be amiss with the environment variables that are configured in Azure -- if it's working locally, and it's not working in the cloud, then there should be some discrepancy. There very well could be a bug in the old package version (1.1.2) as well, so please do upgrade and let us know if that fixes it.

Thanks!

**Comment by Shavivek** [comment]
When I upgrade to semantic-kernel 1.17.1, the app fails to start locally. I get this error trace:

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\viveksh\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\viveksh\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\core\management\commands\runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\core\management\base.py", line 438, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\core\checks\registry.py", line 77, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\urls\resolvers.py", line 634, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\urls\resolvers.py", line 627, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\viveksh\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\VivekSh\Personal\spendtraxApp_New\spendtrax_be\sptx_be\urls.py", line 11, in <module>
    path('', include('spend.urls')),
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\viveksh\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\VivekSh\Personal\spendtraxApp_New\spendtrax_be\spend\urls.py", line 5, in <module>
    from .viewClasses import reccurPaymentsviews, budgetLimitviews, ytdviews, familyMembersviews, smsProcessviews, expenseQueryviews
  File "C:\VivekSh\Personal\spendtraxApp_New\spendtrax_be\spend\viewClasses\smsProcessviews.py", line 12, in <module>
    from azureOAI import llmExpense as lu
  File "C:\VivekSh\Personal\spendtraxApp_New\spendtrax_be\azureOAI\llmExpense.py", line 4, in <module>
    import azureOAI.skKernel as sk
  File "C:\VivekSh\Personal\spendtraxApp_New\spendtrax_be\azureOAI\skKernel.py", line 3, in <module>
    from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\__init__.py", line 31, in <module>
    from semantic_kernel.connectors.ai.open_ai.services.azure_audio_to_text import AzureAudioToText
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\azure_audio_to_text.py", line 10, in <module>
    from semantic_kernel.connectors.ai.open_ai.services.azure_config_base import AzureOpenAIConfigBase
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\azure_config_base.py", line 11, in <module>
    from semantic_kernel.connectors.ai.open_ai.services.open_ai_handler import OpenAIHandler, OpenAIModelTypes
  File "C:\VivekSh\Personal\spendtraxApp_New\sptx_venv\Lib\site-packages\semantic_kernel\connectors\ai\open_ai\services\open_ai_handler.py", line 8, in <module>   
    from openai.lib._parsing._completions import type_to_response_format_param
ModuleNotFoundError: No module named 'openai.lib._parsing'
```
pip check did not result in broken dependencies.

**Comment by moonbox3** [comment]
Hello @Shavivek, thanks for your response. I am not seeing the api-version `2024-07-18` listed for [Azure OpenAI](https://learn.microsoft.com/en-us/azure/ai-services/openai/api-version-deprecation). Can you please try a valid API version, like `2024-07-01-preview` or something newer? Thanks.

**Comment by Shavivek** [comment]
@moonbox3 thanks for this hint. I updated the API version to 2024-08-01-preview and it started working. However, the code on my local box can still work with the older version...

**Comment by moonbox3** [comment]
That's interesting. I don't see any 2024-07-18 API version from Azure (maybe I'm missing something). In any case, I'd stick with a known API version as you've done (2024-08-01-preview) and that should work well going forward. You may also need to use 2024-09-01-preview depending upon your scenario.
