### ISSUE TITLE
dotnet sample 06-memory-and-embeddings.ipynb assumes model name text-embedding-ada-002

### ISSUE THREAD

**Issue by andhesky** [microsoft/semantic-kernel#1047]
**Describe the bug**
AzureOpenAI requires you to deploy models and you can provide a custom name. If there is no model deployed with the name "text-embedding-ada-002" then the "Manually adding memories" section in the dotnet sample 06-memory-and-embeddings.ipynb will fail with the error

```
Error: Microsoft.SemanticKernel.AI.AIException: InvalidRequest: The request is not valid, HTTP status: 404
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGenerateTextEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancel)
at Submission#15.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**To Reproduce**
0. Configure settings as instructed in 0-AI-settings.ipynb. Connect to an Azure Open AI endpoint with an embedding model defined using a name other than "text-embedding-ada-002"
1. Go to '06-memory-and-embeddings.ipynb'
2. Click on 'run for the first three sections'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - IDE: VS Code
 - NuGet Package Version 0.12.207.1-preview

**Additional context**

**Comment by craigomatic** [comment]
@alexchaomander

**Comment by alexchaomander** [comment]
@andhesky I think without introducing more data loaders / changes to the code, you could update the notebook locally and just provide the name of your own custom model deployment? Notebooks can definitely be edited to fit your own needs!

At a future time, we can generalize it. I can put it on our backlog.
