### ISSUE TITLE
Notebook 07-DALL-E-2: Access Denied

### ISSUE THREAD

**Issue by mhackermsft** [microsoft/semantic-kernel#1339]
**Describe the bug**
When following the Notebook sample 07-DALL-E-2 I am getting an Access Denied error when executing the code block under "Generate a (random) image with DALL-E 2.

I have an OpenAI key and the prior notebooks (01-06) work with no issues.  

**To Reproduce**
1. Open Notebooks, dotnet, 07-DALL-E-2
2. Run the first 2 code blocks successfully
3. Run the 3rd code block under the heading of "Generate a (random) image with DALL-E 2.  This will result in an Access Denied error shown below.

Error: Microsoft.SemanticKernel.AI.AIException: Access denied: The request is not authorized, HTTP status: Unauthorized
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.CustomClient.OpenAIClientBase.ExecutePostRequestAsync[T](String url, String requestBody, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.CustomClient.OpenAIClientBase.ExecuteImageGenerationRequestAsync(String url, String requestBody, Func`2 extractResponseFunc, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.ImageGeneration.OpenAIImageGeneration.GenerateImageAsync(String description, Int32 width, Int32 height, String format, Func`2 extractResponse, CancellationToken cancellationToken)
at Submission#31.<<Initialize>>d__0.MoveNext()

**Expected behavior**
Code block executes successfully and generates a random image.

**Comment by craigomatic** [comment]
Hmm, I'm not able to reproduce with my OpenAI key, the notebook works as expected.

Can you confirm that you have DALL-E 2 access with your API key, maybe by using postman or curl? https://platform.openai.com/docs/guides/images/usage?lang=curl

**Comment by mhackermsft** [comment]
> Hmm, I'm not able to reproduce with my OpenAI key, the notebook works as expected.

I am using Azure OpenAI and not the public OpenAI product.  In Azure OpenAI I can go into the DALL-E playground and generate images.  It also shows the Python code for calling the API endpoint.  Is it possible that Semantic Kernel is not yet working with Azure OpenAI?

**Comment by craigomatic** [comment]
Ah, with Azure OpenAI you might be blocked until this PR comes in: #1209

**Comment by mhackermsft** [comment]
Closing issue as it appears that the current release doesn't support DALL-E in Azure Open AI.   Possible follow-up would be to update the notebook to indicate that some samples do not currently work with Azure Open AI.
