### ISSUE TITLE
"RuntimeError: Event loop is closed" on windows Python 3.10

### ISSUE THREAD

**Issue by imfuli** [microsoft/semantic-kernel#1418]
**Describe the bug**

Followed the python README tutorials and other examples provided, it alwasys ran into a runtime error:

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000289E4B2C550>
Traceback (most recent call last):
  File "C:\Program Files\Python3.10\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python3.10\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python3.10\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Program Files\Python3.10\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**To Reproduce**

on Windows system, python version 3.10.4
Follow any of the python examples given in the tutorial, it always run into this Runtime Error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio, VS Code]
 - NuGet Package Version [e.g. 0.1.0]

**Additional context**

**Comment by alexchaomander** [comment]
Thanks for adding the fix to this! We'll take a look soon!

**Comment by cschadewitz** [comment]
I believe this can be closed based on #1416 being merged.
