### ISSUE TITLE
Can I use a custom proxy server address?

### ISSUE THREAD

**Issue by raokun** [microsoft/semantic-kernel#1715]
Can I use a custom proxy server address, such as http://localhost:1002/, to proxy https://api.openai.com/? I cannot access https://api.openai.com/ directly in my country, and the SK API requests will fail internally without a valid proxy setup.
```[tasklist]
### Tasks
```

**Comment by craigomatic** [comment]
Not via config, you could try some of the techniques described here, not sure if it will work though: https://github.com/microsoft/semantic-kernel/discussions/1513#discussioncomment-6198814

**Comment by raokun** [comment]
> Not via config, you could try some of the techniques described here, not sure if it will work though: [#1513 (comment)](https://github.com/microsoft/semantic-kernel/discussions/1513#discussioncomment-6198814)

I set up the proxy according to your code, but it didn't work. It keeps giving me a 502 error, but there's no problem with my proxy when I use it directly.
```
class MyProxy : IWebProxy
    {
        public ICredentials? Credentials { get; set; }
        public Uri? GetProxy(Uri destination)
        {
            var host = destination.Host;
            var port = destination.Port;
            if (host == "api.openai.com" && port == 443)
            {
                return new Uri("http://XXX:4150");
            }
            else
                return null;
        }

        public bool IsBypassed(Uri host)
        {
            return false;
        }
    }
```
ERROR:
```
Microsoft.SemanticKernel.AI.AIException: Unknown error (UnknownError): Something went wrong: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (The proxy tunnel request to proxy 'http://XXX:4150/' failed with status code '502'.") (The proxy tunnel request to proxy 'http://XXX:4150/' failed with status code '502'.") (The proxy tunnel request to proxy 'http://XXX:4150/' failed with status code '502'.") (The proxy tunnel request to proxy 'http://XXX:4150/' failed with status code '502'.")
```

**Comment by craigomatic** [comment]
It looks like you are calling the proxy via http, does it make a difference if you use https instead?

**Comment by raokun** [comment]
> It looks like you are calling the proxy via http, does it make a difference if you use https instead?

i try use https,the error will be this:
```
Microsoft.SemanticKernel.AI.AIException: Unknown error (UnknownError): Something went wrong: Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.
 ---> System.NotSupportedException: Only the 'http', 'socks4', 'socks4a' and 'socks5' schemes are allowed for proxies.
   at System.Net.Http.HttpConnectionPoolManager.SendAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageHandlerStage.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsStreamingAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatStreamingResultsAsync(IEnumerable`1 chat, ChatRequestSettings requestSettings, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatStreamingResultsAsync(IEnumerable`1 chat, ChatRequestSettings requestSettings, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.SemanticKernel.AI.ChatCompletion.ChatCompletionExtensions.GenerateMessageStreamAsync(IChatCompletion chatCompletion, ChatHistory chat, ChatRequestSettings requestSettings, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.AI.ChatCompletion.ChatCompletionExtensions.GenerateMessageStreamAsync(IChatCompletion chatCompletion, ChatHistory chat, ChatRequestSettings requestSettings, CancellationToken cancellationToken)+MoveNext()
```

**Comment by feiyun0112** [comment]
set environment variable HTTPS_PROXY

https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-7.0

#1148

**Comment by firstsaofan** [comment]
I also encountered the same problem. My scenario is that I am an individual developer and do not have the qualifications for the GPT4 API. I hope to use a proxy address when requesting the GPT4 API. Moreover, many models in the current market have APIs that are the same as the parameters of OpenAI's GPT interface. If dynamic request addresses can be passed in, it is also convenient to connect with other models. I would like to know if there are any plans in the future to customize incoming addresses.

**Comment by lemillermicrosoft** [comment]
Additional solution: https://learn.microsoft.com/en-us/semantic-kernel/deploy/use-ai-apis-with-api-management

Re-open if the issue still exists.
