### ISSUE TITLE
.Net: Issues with codesherpa plugin

### ISSUE THREAD

**Issue by samleegithub** [microsoft/semantic-kernel#2330]
**Describe the bug**
https://github.com/iamgreggarcia/codesherpa

codesherpa is a ChatGPT plugin that allows you to run python code similar to the ChatGPT Code Interpreter plugin: https://openai.com/blog/chatgpt-plugins#code-interpreter

When I enable this plugin in Chat Copilot, two issues occur.

**Issue 1:**
Chat Copilot errors when it sees "multipart/form-data" in /.wellknown/openapi.json.

**Issue 2:**
When python code runs that plots using matplotlib, it returns a string like <matplotlib.lines.Line2D object at 0x7fcec5a7a6e0> instead of the plot image.

**To Reproduce**

1. Setup docker instance of codesherpa following the instructions in https://github.com/iamgreggarcia/codesherpa

2. Add codesherpa plugin in Chat Copilot

3. Submit a message in the chat after adding the plugin.

Error message:
```
info: SemanticKernel.Service.CopilotChat.Controllers.ChatController[0]
      Enabling CodeSherpa plugin.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMSE2480TCHC", Request id "0HMSE2480TCHC:00000003": An unhandled exception was thrown by the application.
      Microsoft.SemanticKernel.Skills.OpenAPI.OpenApi.OpenApiDocumentParsingException: Neither of the media types of upload_file_upload_post is supported.
         at Microsoft.SemanticKernel.Skills.OpenAPI.OpenApi.OpenApiDocumentParser.CreateRestApiOperationPayload(String operationId, OpenApiRequestBody requestBody)
         at Microsoft.SemanticKernel.Skills.OpenAPI.OpenApi.OpenApiDocumentParser.CreateRestApiOperations(String serverUrl, String path, OpenApiPathItem pathItem)
         at Microsoft.SemanticKernel.Skills.OpenAPI.OpenApi.OpenApiDocumentParser.ExtractRestApiOperations(OpenApiDocument document)
         at Microsoft.SemanticKernel.Skills.OpenAPI.OpenApi.OpenApiDocumentParser.ParseAsync(Stream stream, Boolean ignoreNonCompliantErrors, CancellationToken cancellationToken)     
         at Microsoft.SemanticKernel.KernelOpenApiExtensions.RegisterOpenApiSkillAsync(IKernel kernel, Stream documentStream, String skillName, OpenApiSkillExecutionParameters executionParameters, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelOpenApiExtensions.ImportOpenApiSkillFromUrlAsync(IKernel kernel, String skillName, Uri url, OpenApiSkillExecutionParameters executionParameters, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelChatGptPluginExtensions.ImportChatGptPluginSkillFromUrlAsync(IKernel kernel, String skillName, Uri url, OpenApiSkillExecutionParameters executionParameters, CancellationToken cancellationToken)
         at SemanticKernel.Service.CopilotChat.Controllers.ChatController.RegisterPlannerSkillsAsync(CopilotChatPlanner planner, Dictionary`2 openApiSkillsAuthHeaders, ContextVariables variables) in C:\Users\samulee\Documents\Microsoft Projects\ITF\chat-copilot\webapi\CopilotChat\Controllers\ChatController.cs:line 244
         at SemanticKernel.Service.CopilotChat.Controllers.ChatController.ChatAsync(IKernel kernel, IHubContext`1 messageRelayHubContext, CopilotChatPlanner planner, Ask ask) in C:\Users\samulee\Documents\Microsoft Projects\ITF\chat-copilot\webapi\CopilotChat\Controllers\ChatController.cs:line 86
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

I figured out Chat Copilot didn't like content: "multipart/form-data" for operationId: "upload_file_upload_post" that is in the openapi.json file for codesherpa.

Excerpt from /.well-known/openapi.json
```
        "/upload": {
            "get": {
                "summary": "Upload Page",
                "operationId": "upload_page_upload_get",
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    }
                }
            },
            "post": {
                "summary": "Upload File",
                "description": "Upload a file.\n\nArgs:\n    file (UploadFile): The uploaded file.\n\nReturns:\n    dict: The result of the file upload process.",
                "operationId": "upload_file_upload_post",
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "$ref": "#/components/schemas/Body_upload_file_upload_post"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Successful Response",
                        "content": {
                            "application/json": {
                                "schema": {}
                            }
                        }
                    },
                    "422": {
                        "description": "Validation Error",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/HTTPValidationError"
                                }
                            }
                        }
                    }
                }
            }
        },
```

6. As a workaround, delete code for uploading in localserver/main.py in codesherpa and redeploy docker container. This fixes the above error for now but this change disables uploading files into the python docker container.

7. Ask in chat to plot x/sin(x)

8. Returns the below message:
```
Here is the plot of the function x/sin(x). [RELATED START]{"result":"[<matplotlib.lines.Line2D object at 0x7fcec5a7a6e0>]"}[RELATED END]
```

**Expected behavior**
1. Chat Copilot should be able to understand how to interact with content: "multipart/form-data" in openapi.json and we are able to upload files to the plugin.
2. Display the plot as an image instead of the text "<matplotlib.lines.Line2D object at 0x7fcec5a7a6e0>".

**Screenshots**
![image](https://github.com/microsoft/chat-copilot/assets/27397725/ced9dea2-3365-433c-86ab-1e3a37abdb38)

**Platform**
 - OS: Windows 11
 - IDE: VS Code
 - Language: C#, Python
 - Source: main branch of repository: https://github.com/microsoft/chat-copilot/

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
