### ISSUE TITLE
.Net: 2nd Embeddings Call from .NET MAUI (just Android) does not get a success 

### ISSUE THREAD

**Issue by arafattehsin** [microsoft/semantic-kernel#2434]
**2nd Embeddings call from .NET MAUI (Android) does not get a success**
I have got a .NET MAUI Project where I am using the Semantic Kernel for embedding and other related stuff (Image Generation etc.). In my first use-case, which is for embedding, finding out a cosine similarity. I am using my code as below:

```
 var origEmbedding = await textEmbeddingGeneration.GenerateEmbeddingsAsync(new List<string> { answer });
 var guessEmbedding = await textEmbeddingGeneration.GenerateEmbeddingsAsync(new List<string> { guessedAnswer });
 var similarity = origEmbedding.First().AsReadOnlySpan().CosineSimilarity(guessEmbedding.First().AsReadOnlySpan());
```
**To Reproduce**
1. Call `textEmbeddingGeneration.GenerateEmbeddingsAsync` for the first time.
2. Again call `textEmbeddingGeneration.GenerateEmbeddingsAsync` for the second time.
3. Catch the exception

Below is the exception:

`{Microsoft.SemanticKernel.AI.AIException: Unknown error (UnknownError): Something went wrong: Cannot access a closed Stream.
 ---> System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.EnsureNotClosed()
   at System.IO.MemoryStream.get_Position()
   at System.Net.Http.HttpContent.LimitMemoryStream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Xamarin.Android.Net.AndroidMessageHandler.WriteRequestContentToOutput(HttpRequestMessage request, HttpURLConnection httpConnection, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 500
   at Xamarin.Android.Net.AndroidMessageHandler.DoProcessRequest(HttpRequestMessage request, URL javaUrl, HttpURLConnection httpConnection, CancellationToken cancellationToken, RequestRedirectionState redirectState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 575
   at Xamarin.Android.Net.AndroidMessageHandler.DoSendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 417
   at Microsoft.SemanticKernel.Reliability.DefaultHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetEmbeddingsAsync(String deploymentOrModelName, EmbeddingsOptions embeddingsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<RunRequestAsync>d__25`1[[Azure.Response`1[[Azure.AI.OpenAI.Embeddings, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.34.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.<RunRequestAsync>d__25`1[[Azure.Response`1[[Azure.AI.OpenAI.Embeddings, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.34.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)`

**Expected behavior**
It should return a correct response.

**Platform**
 - OS: [e.g. Windows]
 - IDE: [e.g. Visual Studio]
 - Language: [e.g. C#]
 - Source: [I've tried past 2 SDKs (it's the same)]

**Additional context**
This works perfectly fine on Windows app (and I assume it should work fine on iOS too). I have also tested in my Polyglot notebooks. It works absolutely well everywhere. 

For more context, this isn't primarily a problem for SK I think but.. as it comes with SDK, developer (who is consuming / using it) can't fix with any of the solutions given here:

1. https://stackoverflow.com/questions/75691627/2nd-android-httpclient-post-throws-system-objectdisposedexception-before-its-ev
2. https://stackoverflow.com/questions/59933234/httpclient-sendasync-throws-objectdisposedexception-on-xamarin-forms-android-but
3. https://stackoverflow.com/questions/76568008/error-in-httpclient-net-maui-when-doing-a-post-with-a-body

**Comment by nacharya1** [comment]
@arafattehsin thanks for letting us know about this, we will investigate.

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
