### ISSUE TITLE
.Net: System.InvalidOperationException: 'Cannot get the value of a token type 'True' as a number.'

### ISSUE THREAD

**Issue by crippledfaith** [microsoft/semantic-kernel#2568]
**Describe the bug**

**To Reproduce**
Running this example https://github.com/microsoft/semantic-kernel/blob/main/samples/notebooks/dotnet/09-memory-with-chroma.ipynb fails on the SearchAsync step with exception deserializing is_reference True as number:

   ```
at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedNumber(JsonTokenType tokenType)
   at System.Text.Json.Utf8JsonReader.TryGetInt16(Int16& value)
   at Microsoft.SemanticKernel.Connectors.Memory.Chroma.ChromaBooleanConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /home/vsts/work/1/s/semantic-kernel/dotnet/src/Connectors/Connectors.Memory.Chroma/ChromaBooleanConverter.cs:line 17
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryReadAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state, Object& value)
   at System.Text.Json.Serialization.Converters.LargeObjectWithParameterizedConstructorConverter`1.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
```

**Platform**
 - OS:  Windows
 - IDE:  Visual Studio
 - Language: C#, .net 7
 - Source: NuGet package Microsoft.SemanticKernel.Connectors.Memory.Chroma version 0.20.230821.4-preview+b4c18f3.
 - Chroma Version 0.4.7

**Additional context**
I have seen the issue reported #2049, Pull Chroma and rerun docker, it seems like they have changed the Choma Implementation again

**Comment by nacharya1** [comment]
@awharrison-28 / @dluc  - can you validate if this a bug or non-bug?

**Comment by dmytrostruk** [comment]
Closing as fixed in this PR: https://github.com/microsoft/semantic-kernel/pull/2796.
Supporting Chroma version 0.4.10 now.
