### ISSUE TITLE
.Net: 07-DALL-E-2 Notebook in dotnet contains error in code when creating Kernel

### ISSUE THREAD

**Issue by Roybott** [microsoft/semantic-kernel#2839]
The dotnet code to create the kernel in the 07-DALL-E-2 notebook has an error when using OpenAI (not Azure), which results in the following error message:

> Error: System.ArgumentException: The value cannot be an empty string or composed entirely of whitespace. (Parameter 'apiKey')
at Microsoft.SemanticKernel.Diagnostics.Verify.ThrowArgumentWhiteSpaceException(String paramName)
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.OpenAIClientBase..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
at Microsoft.SemanticKernel.Connectors.AI.OpenAI.TextEmbedding.OpenAITextEmbeddingGeneration..ctor(String modelId, String apiKey, String organization, HttpClient httpClient, ILoggerFactory loggerFactory)
at Microsoft.SemanticKernel.OpenAIKernelBuilderExtensions.<>c__DisplayClass6_0.<WithOpenAITextEmbeddingGenerationService>b__0(ILoggerFactory loggerFactory, KernelConfig config)
at Microsoft.SemanticKernel.KernelBuilder.<>c__DisplayClass21_0`1.<WithAIService>b__0()
at Microsoft.SemanticKernel.Services.NamedServiceProvider`1.GetService[T](String name)
at Microsoft.SemanticKernel.Kernel.GetService[T](String name)
at Submission#10.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

due to the code:

`else
{
    builder.WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", orgId);
    builder.WithOpenAITextCompletionService("gpt-3.5-turbo", orgId);
    builder.WithOpenAIImageGenerationService(apiKey, orgId);
}`

<img width="502" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/26841868/3f50f486-77d0-4e96-9b4f-8690eca7b5ba">

The issue is the 'orgId' is passed in as the second parameter for the first two lines rather than the apiKey, the correct code should be:

`else
{
    builder.WithOpenAITextEmbeddingGenerationService("text-embedding-ada-002", apiKey, orgId);
    builder.WithOpenAITextCompletionService("gpt-3.5-turbo", apiKey, orgId);
    builder.WithOpenAIImageGenerationService(apiKey, orgId);
}`

<img width="552" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/26841868/436da097-d5b9-49bd-bfe5-4b32732bc88e">

**Comment by Roybott** [comment]
It also seems like other parts of this notebook are broken and it should be fully reviewed.

For example, when running the next code block that generates an image, I got an error about the model not being supported on the text completion endpoint and that it suggested calling the Chat completion service instead. 

This can be fixed by changing the code in the kernel setup code block to use `builder.WithOpenAIChatCompletionService` instead of `WithOpenAITextCompletionService`.

**Comment by evchaki** [comment]
@Roybott - thanks for finding this.  Feel free to do a PR if you can on this.

**Comment by Roybott** [comment]
> @Roybott - thanks for finding this. Feel free to do a PR if you can on this.

I created a PR here: https://github.com/microsoft/semantic-kernel/pull/3065
