### ISSUE TITLE
.Net: Deserializing exception for WithHuggingFaceTextEmbeddingGenerationService 

### ISSUE THREAD

**Issue by ashishwebt** [microsoft/semantic-kernel#2999]
**Describe the bug**
When I try to generate embedding using WithHuggingFaceTextEmbeddingGenerationService I'm getting JSON parse error for returned embedding by https://api-inference.huggingface.co/pipeline/feature-extraction/sentence-transformers/all-MiniLM-L6-v2 endpoint.

**To Reproduce**
Add WithHuggingFaceTextEmbeddingGenerationService to kernel with model /sentence-transformers/all-MiniLM-L6-v2,
retrieve ITextEmbeddingGeneration service and call GenerateEmbeddingAsync

Or

Run following code.

      internal class Program
      {
          static async Task Main(string[] args)
          {
                  var CERT_PATH = "PATH_TO_CERT";
                  var handler = new HttpClientHandler();
                  handler.ClientCertificateOptions = ClientCertificateOption.Manual;
                  handler.SslProtocols = SslProtocols.Tls12;
                  handler.ClientCertificates.Add(new X509Certificate2(CERT_PATH));
                  var client = new HttpClient(handler);
                  client.BaseAddress = new Uri("https://api-inference.huggingface.co/pipeline/feature-extraction");
          
                  IKernel kernel = Kernel.Builder
                          .WithHuggingFaceTextEmbeddingGenerationService("sentence-transformers/all-MiniLM-L6-v2", httpClient: client)
          
                .Build();
                  var embedinggenerator = kernel.GetService<ITextEmbeddingGeneration>();
                  var embeding = await embedinggenerator.GenerateEmbeddingAsync("british short hair");
      
      
          }
      }

**Expected behavior**
Embedings shold be return by GenerateEmbeddingAsync method
**Screenshots**

**Platform**
 - OS: Windows
 - IDE:  Visual Studio
 - Language: C#
 - Source: [e.g. NuGet package version Microsoft.SemanticKernel.Connectors.AI.HuggingFace 0.24.230918.1-preview]

**Additional context**

System.Text.Json.JsonException
  HResult=0x80131500
  Message=The JSON value could not be converted to Microsoft.SemanticKernel.Connectors.AI.HuggingFace.TextEmbedding.TextEmbeddingResponse. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Microsoft.SemanticKernel.Connectors.AI.HuggingFace.TextEmbedding.HuggingFaceTextEmbeddingGeneration.<ExecuteEmbeddingRequestAsync>d__7.MoveNext()
   at Microsoft.SemanticKernel.Connectors.AI.HuggingFace.TextEmbedding.HuggingFaceTextEmbeddingGeneration.<GenerateEmbeddingsAsync>d__6.MoveNext()
   at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.<GenerateEmbeddingAsync>d__0`2.MoveNext()
   at Semantic.Program.<Main>d__0.MoveNext() in C:\Work\Start\Semantic\Semantic\Program.cs:line 30

**Comment by ashishwebt** [comment]
Hi,
I have tracked this error in following file on line 108.
https://github.com/microsoft/semantic-kernel/blob/main/dotnet/src/Connectors/Connectors.AI.HuggingFace/TextEmbedding/HuggingFaceTextEmbeddingGeneration.cs

I have fixed this in my Repo can I open PR?
https://github.com/microsoft/semantic-kernel/compare/main...ashishwebt:semantic-kernel:main?diff=split

**Also, as different models may have different output response structure this method should also have generic overload may be?**
![image](https://github.com/microsoft/semantic-kernel/assets/120636885/707eb0ad-978b-47cf-bc68-34e2d45d7304)Hi,

**Comment by dmytrostruk** [comment]
> I have fixed this in my Repo can I open PR?

@ashishwebt Sure, feel free to open new PR if you resolved this issue! Thanks a lot!

> Also, as different models may have different output response structure this method should also have generic overload may be?

I thought that all embedding HuggingFace API endpoints have the same response structure, isn't it the case? If no, then we should probably re-design it to be generic and handle different response formats.

**Comment by buzahid** [comment]
I updated my sdk to v 0.24.230918 and the Kernel.WithHuggingFace___ methods no longer exist. Can anyone shed some light on this?

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
