### ISSUE TITLE
.Net: ImportOpenAIPluginFunctionsAsync throws SKExeption on user_http

### ISSUE THREAD

**Issue by tolervik** [microsoft/semantic-kernel#3468]
**Describe the bug**
if the plugin .well-known/ai-plugin.json endpoint returns an auth node with type = user_http

"auth": {
  "type": "user_http",
    "authorization_type": "Bearer"
}

IKernel.ImportOpenAIPluginFunctionsAsync  trows

Microsoft.SemanticKernel.Diagnostics.SKException
  HResult=0x80131500
  Message=Parsing of Open AI manifest failed.
  Source=Microsoft.SemanticKernel.Functions.OpenAPI
  StackTrace:
   at Microsoft.SemanticKernel.Functions.OpenAPI.OpenAI.KernelOpenAIPluginExtensions.<ImportAsync>d__3.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\src\Functions\Functions.OpenAPI\OpenAI\KernelOpenAIPluginExtensions.cs:line 139
   at Microsoft.SemanticKernel.Functions.OpenAPI.OpenAI.KernelOpenAIPluginExtensions.<ImportOpenAIPluginFunctionsAsync>d__1.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\src\Functions\Functions.OpenAPI\OpenAI\KernelOpenAIPluginExtensions.cs:line 84
   at Example21_ChatGptPlugins.<RunChatGptPluginAsync>d__1.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\samples\KernelSyntaxExamples\Example21_ChatGPTPlugins.cs:line 28
   at Example21_ChatGptPlugins.<RunAsync>d__0.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\samples\KernelSyntaxExamples\Example21_ChatGPTPlugins.cs:line 17
   at Program.<SafeWaitAsync>d__4.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\samples\KernelSyntaxExamples\Program.cs:line 101
   at Program.<RunExamplesAsync>d__1.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\samples\KernelSyntaxExamples\Program.cs:line 60
   at Program.<Main>d__0.MoveNext() in D:\source\repos\samples\semantic-kernel\dotnet\samples\KernelSyntaxExamples\Program.cs:line 30

  This exception was originally thrown at this call stack:
    [External Code]
    Microsoft.SemanticKernel.Functions.OpenAPI.OpenAI.KernelOpenAIPluginExtensions.ImportAsync(Microsoft.SemanticKernel.IKernel, string, string, Microsoft.SemanticKernel.Functions.OpenAPI.OpenAI.OpenAIFunctionExecutionParameters, System.Threading.CancellationToken) in KernelOpenAIPluginExtensions.cs

Inner Exception 1:
JsonException: The JSON value could not be converted to Microsoft.SemanticKernel.Functions.OpenAPI.OpenAI.OpenAIAuthenticationType. Path: $.type | LineNumber: 0 | BytePositionInLine: 19.

**To Reproduce**
1: modify Example21_ChatGPTPlugins to access a plugin that returns auth type "user_http"

**Expected behavior**
looks like the enum OpenAIAuthenticationType is not parsed correctly

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022 17.8.0 Preview 7.0 
 - Language: C#

**Comment by matthewbolanos** [comment]
@dehoward, would you be able to take a look at this and see if it's related to your recent auth changes?

**Comment by dehoward** [comment]
this will be fixed by #3423 which should merge very soon (next day or so).

**Comment by stephentoub** [comment]
> this will be fixed by #3423 which should merge very soon (next day or so).

@dehoward, is this now fixed?

**Comment by dehoward** [comment]
@stephentoub yes, it ended up being fixed by #3716. closing.
