### ISSUE TITLE
.Net: Gpt-3.5-turbo and other LLMs do not follow prompt breaking planer

### ISSUE THREAD

**Issue by MaxAkbar** [microsoft/semantic-kernel#3682]
**Describe the bug**
When using other language models and gpt-3.5-turbo, the planner breaks due to invalid XML. This occurs because the prompt is not being followed, resulting in text describing the XML. Here is an example response from gpt-3.5-turbo:

Here is the code being executed (The code example is from [11-Planner](https://github.com/MicrosoftDocs/semantic-kernel-docs/tree/main/samples/dotnet/11-Planner)).
When the code is executed against gpt-3.5-turbo it generates the following response. The code throws an exception as the regex can't parse the response into valid XML. The following is the response from gpt-3.5-turbo.

```
To create a plan to satisfy the given goal, we can follow these steps:

1. Start by creating a <plan> element.
2. Since the goal involves calculating the increase in investment, we can use the MathPlugin.Multiply function to calculate the increase amount.
3. We need to multiply the investment amount by the percentage increase. To do this, we can use the MathPlugin.Multiply function with the inputs being the investment amount and the percentage increase.
4. Save the result of the multiplication using the setContextVariable attribute.
5. Next, we need to subtract the amount spent on the latte from the increased investment amount. We can use the MathPlugin.Subtract function with the inputs being the increased investment amount and the amount spent on the latte.
6. Save the result of the subtraction using the setContextVariable attribute.
7. Finally, append the result of the subtraction to the plan result using the appendToResult attribute.

Here is the XML plan to satisfy the given goal:

<plan>
    <!-- Calculate the increase amount -->
    <function.MathPlugin.Multiply input="2130.23" number2="1.23" setContextVariable="INCREASE_AMOUNT"/>
    <!-- Subtract the amount spent on the latte -->
    <function.MathPlugin.Subtract input="$INCREASE_AMOUNT" number2="5" setContextVariable="FINAL_AMOUNT" appendToResult="RESULT__FINAL_AMOUNT"/>
</plan>
```

**To Reproduce**

1. Run the following code against gpt-3.5-turbo:
```
using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Planning;

using ILoggerFactory loggerFactory = LoggerFactory.Create(builder =>
{
    builder
        .SetMinimumLevel(0)
        .AddDebug();
});

// Create kernel
Kernel kernel = new KernelBuilder()
    // Add a text or chat completion service using either:
    // .WithAzureTextCompletionService()
    // .WithAzureChatCompletionService()
    // .WithOpenAITextCompletionService()
    // .WithOpenAIChatCompletionService()
    .WithOpenAIChatCompletionService("gpt-3.5-turbo", "API_KEY")
    .WithLoggerFactory(loggerFactory)
    .Build();

// Add the math plugin
var mathPlugin = kernel.CreatePluginFromObject(new OrchestratorPlugin.MathPlugin.Math(), "MathPlugin");

kernel.Plugins.Add(mathPlugin);

// Create a planner
var planner = new SequentialPlanner(kernel);

var ask = "If my investment of 2130.23 dollars increased by 23%, how much would I have after I spent $5 on a latte?";
var plan = await planner.CreatePlanAsync(ask);

Console.WriteLine("Plan:\n");
Console.WriteLine(JsonSerializer.Serialize(plan, new JsonSerializerOptions { WriteIndented = true }));

var result = await kernel.RunAsync(plan);

Console.WriteLine("Plan results:");
Console.WriteLine(result.GetValue<string>()!.Trim());
```
2. See error
```
Microsoft.SemanticKernel.SKException
  HResult=0x80131500
  Message=Unable to create plan for goal with available functions.
Goal:If my investment of 2130.23 dollars increased by 23%, how much would I have after I spent $5 on a latte?
Functions:
MathPlugin.Add:
  description: Add two numbers
  inputs:
    - input: The first number to add
    - number2: The second number to add

MathPlugin.Divide:
  description: Divide two numbers
  inputs:
    - input: The first number to divide from
    - number2: The second number to divide by

MathPlugin.Multiply:
  description: Multiply two numbers. When increasing by a percentage, don't forget to add 1 to the percentage.
  inputs:
    - input: The first number to multiply
    - number2: The second number to multiply

MathPlugin.Sqrt:
  description: Take the square root of a number
  inputs:
    - input: 

MathPlugin.Subtract:
  description: Subtract two numbers
  inputs:
    - input: The first number to subtract from
    - number2: The second number to subtract away
  Source=Microsoft.SemanticKernel.Planners.Core
  StackTrace:
   at Microsoft.SemanticKernel.Planning.SequentialPlanner.<CreatePlanCoreAsync>d__4.MoveNext() in C:\Users\maxim\source\repos\semantic-kernel\dotnet\src\Planners\Planners.Core\Sequential\SequentialPlanner.cs:line 105
   at Microsoft.SemanticKernel.Planning.PlannerInstrumentation.<CreatePlanAsync>d__3`2.MoveNext() in C:\Users\maxim\source\repos\semantic-kernel\dotnet\src\Planners\Planners.Core\PlannerInstrumentation.cs:line 55
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\maxim\source\repos\semantic-kernel\dotnet\Max\SimpleGptKernelPlaner\Program.cs:line 33
   at Program.<Main>(String[] args)

  This exception was originally thrown at this call stack:
    System.Xml.XmlTextReaderImpl.Throw(System.Exception)
    System.Xml.XmlTextReaderImpl.Throw(string, string[])
    System.Xml.XmlTextReaderImpl.ThrowTagMismatch(System.Xml.XmlTextReaderImpl.NodeData)
    System.Xml.XmlTextReaderImpl.ParseEndElement()
    System.Xml.XmlTextReaderImpl.ParseElementContent()
    System.Xml.XmlLoader.LoadNode(bool)
    System.Xml.XmlLoader.LoadDocSequence(System.Xml.XmlDocument)
    System.Xml.XmlDocument.Load(System.Xml.XmlReader)
    System.Xml.XmlDocument.LoadXml(string)
    Microsoft.SemanticKernel.Planning.SequentialPlanParser.ToPlanFromXml(string, string, System.Func<string, string, Microsoft.SemanticKernel.KernelFunction>, bool) in SequentialPlanParser.cs

Inner Exception 1:
SKException: Failed to parse plan xml strings: 'To create a plan to satisfy the given goal, we can follow these steps:

1. Start by creating a <plan> element.
2. Check if the MathPlugin.Multiply function is available in the [AVAILABLE FUNCTIONS] list. If it is, use it to calculate the increased amount after the investment.
3. Check if the MathPlugin.Subtract function is available. If it is, use it to subtract the amount spent on the latte.
4. Append an "END" XML comment at the end of the plan.
5. Output the valid XML plan.

Here is the XML plan to satisfy the goal:

<plan>
    <!-- Calculate the increased amount after the investment -->
    <function.MathPlugin.Multiply input="2130.23" number2="1.23" setContextVariable="INCREASED_AMOUNT"/>
    <!-- Subtract the amount spent on the latte -->
    <function.MathPlugin.Subtract input="$INCREASED_AMOUNT" number2="5" appendToResult="RESULT__FINAL_AMOUNT"/>
</plan>' or '<plan> element.
2. Check if the MathPlugin.Multiply function is available in the [AVAILABLE FUNCTIONS] list. If it is, use it to calculate the increased amount after the investment.
3. Check if the MathPlugin.Subtract function is available. If it is, use it to subtract the amount spent on the latte.
4. Append an "END" XML comment at the end of the plan.
5. Output the valid XML plan.

Here is the XML plan to satisfy the goal:

<plan>
    <!-- Calculate the increased amount after the investment -->
    <function.MathPlugin.Multiply input="2130.23" number2="1.23" setContextVariable="INCREASED_AMOUNT"/>
    <!-- Subtract the amount spent on the latte -->
    <function.MathPlugin.Subtract input="$INCREASED_AMOUNT" number2="5" appendToResult="RESULT__FINAL_AMOUNT"/>
</plan>'

Inner Exception 2:
XmlException: The 'plan' start tag on line 1 position 7 does not match the end tag of 'xml'. Line 14, position 10.
```

**Expected behavior**
I expect that I get the result of the planer outputted in the command line in JSON and the result of the planner.

**Screenshots**
No screenshot is needed.

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022 Community
 - Language: C#
 - Source: main branch of repository

**Additional context**
No additional context.

**Comment by michelschep** [comment]
Same error here (with Rider 3.2).
I'm using gpt-3.5-turbo as a model.
Model is hosted in OpenAI (so kernel is configured like this: .WithOpenAIChatCompletionService("gpt-3.5-turbo", openAIKey)).

Doing the same thing with the model (gpt-35-turbo version 0301) hosted in Azure then a plan (with two steps) is created:
var plan = await planner.CreatePlanAsync(ask);

However the result returned by RunAsync is null:
var result = await kernel.RunAsync(plan);

**Comment by MaxAkbar** [comment]
Ok I will take a look later today.
