### ISSUE TITLE
.Net: Improve timout error for AI connectors

### ISSUE THREAD

**Issue by Alerinos** [microsoft/semantic-kernel#3700]
**Describe the bug**
Very often he receives a timeout.
```
System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji..
 ---> System.Net.Sockets.SocketException (995): Operacja We/Wy została przerwana z powodu zakończenia wątku lub żądania aplikacji.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Reliability.Basic.BasicHttpRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.SemanticFunction.RunPromptAsync(AIRequestSettings requestSettings, SKContext context, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.SemanticFunction.InvokeAsync(SKContext context, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Kernel.RunAsync(ContextVariables variables, CancellationToken cancellationToken, ISKFunction[] pipeline)
   at Zonit.Plugins.AI.Infrastructure.AI.Repositories.HeaderRepository.GetAsync(String header, String title, String description, String content, String culture) in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.AI.Infrastructure\AI\Repositories\HeaderRepository.cs:line 66
   at Zonit.Plugins.AI.Application.Services.ArticleService.GetAsync(ArticleModel model) in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.Ai.Application\Services\ArticleService.cs:line 25
   at Zonit.Plugins.AI.Application.Services.RunQueueService.<StartAsync>b__6_0() in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.Ai.Application\Services\RunQueueService.cs:line 55
```

Version: 1.0.0-beta8
```cs
    readonly OpenAIRequestSettings requestSettings = new()
    {
        ExtensionData = {
                {"MaxTokens", 4096},
                {"Temperature", 0.6},
                {"TopP", 0.8},
                {"PresencePenalty", 0.3},
                {"FrequencyPenalty", 0.3}
            }
    };

    public async Task<Article?> GetAsync(string topic, string culture, int headers)
    {
        var variables = new ContextVariables();
        variables.Set("Topic", topic);
        variables.Set("Culture", culture);
        variables.Set("HeadersCount", headers.ToString());

        var kernel = new KernelBuilder()
            .WithOpenAIChatCompletionService(
                "gpt-3.5-turbo-1106",
                "xxxx"
            )
            .Build();

        var getIntentFunction = kernel
            .CreateSemanticFunction(Prompt, requestSettings, "GetIntent");

        var result = await kernel
            .RunAsync(variables, getIntentFunction);

        var json = JsonSerializer.Deserialize<Article>(result.ToString());

        return json;
    }
```
The problem often occurs when I use a function many times.
It generates it 6 times, for example.

**Comment by matthewbolanos** [comment]
This can happen if you end up getting throttled by OpenAI. Are you able to try adding one of the [retry handlers](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example08_RetryHandler.cs) to see if it helps your scenario?

**Comment by Alerinos** [comment]
I started searching for the problem on Google. This is a fairly common problem with Azure. Why am I using Azure when I used the OpenAI api? I should be connecting to them not Azure....

Also I added my own HttpClient and set the time out to 10 minutes, after setting the time out to 10 it is ignored and I still have 100 seconds....

```cs
        var httpClient = new HttpClient
        {
            Timeout = TimeSpan.FromMinutes(10)
        };

        _kernel = new KernelBuilder()
            .WithOpenAIChatCompletionService(
                "gpt-3.5-turbo-1106",
                "sk-xxx",
                 httpClient: httpClient
            )
            .Build();
```

The problem is strange, sometimes it will generate a response very fast, if the script does not execute in 30 seconds it means it will not execute at all. The problem is random, I only do a few queries to the API. In such a quantity it is not suitable for production.... In the version before 1.0 there were no such problems, I am forced to return to a lower version....

**Comment by Alerinos** [comment]
Now I received such an error:
```
Microsoft.SemanticKernel.Diagnostics.HttpOperationException: The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 94b02f53d7316c40e81e519f408556ba in your email.)
Status: 500 (Internal Server Error)

Content:
{
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 94b02f53d7316c40e81e519f408556ba in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}


Headers:
Date: Tue, 28 Nov 2023 00:42:40 GMT
Connection: keep-alive
Access-Control-Allow-Origin: REDACTED
openai-organization: REDACTED
openai-processing-ms: REDACTED
openai-version: REDACTED
Strict-Transport-Security: REDACTED
x-ratelimit-limit-requests: REDACTED
x-ratelimit-limit-tokens: REDACTED
x-ratelimit-limit-tokens_usage_based: REDACTED
x-ratelimit-remaining-requests: REDACTED
x-ratelimit-remaining-tokens: REDACTED
x-ratelimit-remaining-tokens_usage_based: REDACTED
x-ratelimit-reset-requests: REDACTED
x-ratelimit-reset-tokens: REDACTED
x-ratelimit-reset-tokens_usage_based: REDACTED
X-Request-ID: REDACTED
CF-Cache-Status: REDACTED
Set-Cookie: REDACTED
Server: cloudflare
CF-RAY: REDACTED
Alt-Svc: REDACTED
Content-Type: application/json
Content-Length: 366

 ---> Azure.RequestFailedException: The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 94b02f53d7316c40e81e519f408556ba in your email.)
Status: 500 (Internal Server Error)

Content:
{
  "error": {
    "message": "The server had an error processing your request. Sorry about that! You can retry your request, or contact us through our help center at help.openai.com if you keep seeing this error. (Please include the request ID 94b02f53d7316c40e81e519f408556ba in your email.)",
    "type": "server_error",
    "param": null,
    "code": null
  }
}


Headers:
Date: Tue, 28 Nov 2023 00:42:40 GMT
Connection: keep-alive
Access-Control-Allow-Origin: REDACTED
openai-organization: REDACTED
openai-processing-ms: REDACTED
openai-version: REDACTED
Strict-Transport-Security: REDACTED
x-ratelimit-limit-requests: REDACTED
x-ratelimit-limit-tokens: REDACTED
x-ratelimit-limit-tokens_usage_based: REDACTED
x-ratelimit-remaining-requests: REDACTED
x-ratelimit-remaining-tokens: REDACTED
x-ratelimit-remaining-tokens_usage_based: REDACTED
x-ratelimit-reset-requests: REDACTED
x-ratelimit-reset-tokens: REDACTED
x-ratelimit-reset-tokens_usage_based: REDACTED
X-Request-ID: REDACTED
CF-Cache-Status: REDACTED
Set-Cookie: REDACTED
Server: cloudflare
CF-RAY: REDACTED
Alt-Svc: REDACTED
Content-Type: application/json
Content-Length: 366

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(String deploymentOrModelName, ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsync(ChatHistory chat, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGetChatResultsAsTextAsync(String text, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.SemanticFunction.RunPromptAsync(AIRequestSettings requestSettings, SKContext context, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.SemanticFunction.InvokeAsync(SKContext context, AIRequestSettings requestSettings, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Kernel.RunAsync(ContextVariables variables, CancellationToken cancellationToken, ISKFunction[] pipeline)
   at Zonit.Plugins.AI.Infrastructure.AI.Repositories.HeaderRepository.GetAsync(String header, String title, String description, String content, String culture) in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.AI.Infrastructure\AI\Repositories\HeaderRepository.cs:line 66
   at Zonit.Plugins.AI.Application.Services.ArticleService.GetAsync(ArticleModel model) in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.Ai.Application\Services\ArticleService.cs:line 25
   at Zonit.Plugins.AI.Application.Services.RunQueueService.<StartAsync>b__6_0() in E:\Git\Stand\Source\Plugins\AI\Zonit.Plugins.Ai.Application\Services\RunQueueService.cs:line 55
   ```

**Comment by DrEight** [comment]
Yesterday I had the same problem with the same model, but in Azure. Is the reason the same ?

**Comment by jmurkothintel** [comment]
@matthewbolanos  Would you happen to have an update on this bug

**Comment by markwallace-microsoft** [comment]
All .Net issues prior to 1-Dec-2023 are being closed. Please re-open, if this issue is still relevant to the .Net Semantic Kernel 1.x release. In the future all issues that are inactive for more than 90 days will be labelled as 'stale' and closed 14 days later.
