### ISSUE TITLE
.Net: Example70_Assistant Fails with  Microsoft.SemanticKernel.KernelException (WithPromptFunctions)

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#3787]
**Describe the bug**
```
Unhandled exception. Microsoft.SemanticKernel.KernelException: Service of type Microsoft.SemanticKernel.AI.TextCompletion.ITextCompletion not registered.
   at Microsoft.SemanticKernel.Services.OrderedAIServiceSelector.SelectAIService[T](Kernel kernel, KernelFunction function, KernelArguments arguments) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\SemanticKernel.Abstractions\Services\OrderedAIServiceSelector.cs:line 68
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.RenderPromptAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\SemanticKernel.Core\Functions\KernelFunctionFromPrompt.cs:line 225
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\SemanticKernel.Core\Functions\KernelFunctionFromPrompt.cs:line 129
   at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\SemanticKernel.Abstractions\Functions\KernelFunction.cs:line 128
   at Microsoft.SemanticKernel.Experimental.Assistants.Internal.ChatRun.<>c__DisplayClass16_0.<<ProcessFunctionStepAsync>g__InvokeFunctionCallAsync|0>d.MoveNext() in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\Experimental\Assistants\Internal\ChatRun.cs:line 153
--- End of stack trace from previous location ---
   at Microsoft.SemanticKernel.Experimental.Assistants.Internal.ChatRun.ProcessFunctionStepAsync(String callId, FunctionDetailsModel functionDetails, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\Experimental\Assistants\Internal\ChatRun.cs:line 130
   at Microsoft.SemanticKernel.Experimental.Assistants.Internal.ChatRun.GetResultAsync(CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\Experimental\Assistants\Internal\ChatRun.cs:line 57
   at Microsoft.SemanticKernel.Experimental.Assistants.Internal.ChatThread.InvokeAsync(IAssistant assistant, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\src\Experimental\Assistants\Internal\ChatThread.cs:line 77
   at Example70_Assistant.ChatAsync(String resourcePath, IKernelPlugin plugin, String[] messages) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example70_Assistant.cs:line 147
   at Example70_Assistant.RunWithPromptFunctionsAsync() in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example70_Assistant.cs:line 80
   at Example70_Assistant.RunAsync() in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example70_Assistant.cs:line 38
   at Program.SafeWaitAsync(Task task, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 101
   at Program.RunExamplesAsync(String filter, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 60
   at Program.Main(String[] args) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 30
   at Program.<Main>(String[] args)
```

**To Reproduce**
1. Configure environment
1. dotnet run  Example70_Assistant

**Expected behavior**
No exception.

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: [e.g. C#, Python]
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by crickman** [comment]
Did analysis...have fix.
