### ISSUE TITLE
.Net: Example45_MultiStreamingChatCompletion fails with System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by crickman** [microsoft/semantic-kernel#3810]
**Describe the bug**
```
Unhandled exception. System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 30.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Example45_MultiStreamingChatCompletion.StreamingChatCompletionAsync(IChatCompletion chatCompletion) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example45_MultiStreamingChatCompletion.cs:line 67
   at Example45_MultiStreamingChatCompletion.AzureOpenAIMultiStreamingChatCompletionAsync() in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example45_MultiStreamingChatCompletion.cs:line 33
   at Example45_MultiStreamingChatCompletion.RunAsync() in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Example45_MultiStreamingChatCompletion.cs:line 20
   at Program.SafeWaitAsync(Task task, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 101
   at Program.RunExamplesAsync(String filter, CancellationToken cancellationToken) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 60
   at Program.Main(String[] args) in C:\Users\crickman\source\repos\semantic-kernel1\dotnet\samples\KernelSyntaxExamples\Program.cs:line 30
   at Program.<Main>(String[] args)
```

**To Reproduce**
1. Configure environment
1. `dotnet run Example45_MultiStreamingChatCompletion`

**Expected behavior**
Sample completes without exception

**Platform**
 - OS: WIndows
 - IDE: Console
 - Language: C#
 - Source: V1 Bug Bash

**Comment by RogerBarreto** [comment]
Resolved in PR #3885
