### ISSUE TITLE
.Net: HandlebarsPlanner error: Microsoft.SemanticKernel.KernelException: 'Invalid parameter count for function Brainstorm. 1 were specified but 0 are required.

### ISSUE THREAD

**Issue by MikeYeager** [microsoft/semantic-kernel#4203]
**Describe the bug**
Microsoft.SemanticKernel.KernelException: 'Invalid parameter count for function Brainstorm. 1 were specified but 0 are required.' when executing the basic HandlebarsPlanner example.

**To Reproduce**
```
            var builder = new KernelBuilder();
            builder.Services
                .AddAzureOpenAIChatCompletion(
                    "gpt-4",
                    "gpt-4",
                    _endpointSweden,
                    _apiKeySweden);
            var kernel = builder.Build();
            var functionDirectory = Path.Combine(Directory.GetCurrentDirectory(), "Plugins", "Writer");
            var semanticFunctions = kernel.ImportPluginFromPromptDirectory(functionDirectory);
            var planner = new HandlebarsPlanner();
            var ask = "Tomorrow is Valentine's day. I need to come up with a few date ideas. My significant other likes poems so write them in the form of a poem.";
            var plan = await planner.CreatePlanAsync(kernel, ask);
            Console.WriteLine(plan);
            var result = plan.Invoke(kernel, new KernelArguments());
            Console.WriteLine(result);
```
It outputs this plan, then throws the exception:
{{!-- Step 1: Initialize the date ideas --}}
{{set "dateIdeas" (Writer-Brainstorm "Valentine's day date ideas")}}

{{!-- Step 2: Loop through each date idea --}}
{{#each (get "dateIdeas")}}
  {{!-- Step 3: Write a short poem for each date idea --}}
  {{json (Writer-ShortPoem this)}}
{{/each}}

**Platform**
 - OS: Windows 11 Pro
 - IDE: Visual Studio 2022
 - Language: C#
 - Source: SK NuGet package version 0.1.0-rc3, SK.Planners.Handlebars package version 0.1.0-rc3

**Additional context**
The Writer plugins are prompts taken directly from the dotnet samples with no modifications. The Brainstorm template looks like this:
Must: brainstorm ideas and create a list.
Must: use a numbered list.
Must: only one list.
Must: end list with ##END##
Should: no more than 10 items.
Should: at least 3 items.
Topic: {{$INPUT}}
Start.

**Comment by sanchez** [comment]
If you breakpoint after the Console Logging your plan, what's the value of your `Prompt` property on the plan? I have a feeling that the plan has no arguments listed for your brainstorm function.

**Comment by MikeYeager** [comment]
@sanchez I saw that report, but I'm not sure it's the same issue. Here is that Prompt:
<system~>## Instructions
Explain how to achieve the user's goal with the available helpers with a Handlebars template.

## Example
If the user wanted you to generate 10 random numbers and use them in another helper, you could answer with the following.</system~>
<user~>Please show me how to write a Handlebars template that achieves the following goal.

## Goal
I want you to generate 10 random numbers and send them to another helper.
</user~>
<assistant~>Here's the Handlebars template that achieves the goal:
```handlebars
{{!-- Step 1: Initialize the count --}}
{{set
  "count"
  10
}}
{{!-- Step 2: Loop using the count --}}
{{#each
  (range
    1
    (get
      "count"
    )
  )
}}
  {{set
    "index"
    this
  }}
  {{!-- Step 3: Create random number --}}
  {{set
    "randomNumber"
    (Example-Random
      seed=(get
        "index"
      )
    )
  }}
  {{!-- Step 4: Call example helper with random number and print the result to the screen --}}
  {{json
    (Example-Helper
      input=(get
        "randomNumber"
      )
    )
  }}
{{/each}}
```</assistant~>
<system~>Now let's try the real thing.</system~>
<user~>Please show me how to write a Handlebars template that achieves the following goal with the available helpers.

## Goal
Tomorrow is Valentine's day. I need to come up with a few date ideas. My significant other likes poems so write them in the form of a poem.

## Out-of-the-box helpers
The following helpers are available to you:
- `{{#if}}{{/if}}`
- `{{#unless}}{{/unless}}`
- `{{#each}}{{/each}}`
- `{{#with}}{{/with}}`

## Loop helpers
If you need to loop through a list of values with `{{#each}}`, you can use the following helpers:
- `{{range}}` – Generates a sequence of integral numbers within a specified range, inclusive of last value.
- `{{array}}` – Generates an array of values from the given values.

IMPORTANT: `range` and `array` are the only supported data structures. Others like `hash` are not supported. Also, you cannot use any methods or properties on the built-in data structures, such as `array.push` or `range.length`.

## Math helpers
If you need to do basic operations, you can use these two helpers with numerical values:
- `{{add}}` – Adds two values together.
- `{{subtract}}` – Subtracts the second value from the first.

## Comparison helpers
If you need to compare two values, you can use the `{{equal}}` helper.
To use the math and comparison helpers, you must pass in two positional values. For example, to check if the variable `var` is equal to number `1`, you would use the following helper like so: `{{#if (equal var 1)}}{{/if}}`.

## Variable helpers
If you need to create or retrieve a variable, you can use the following helpers:
- `{{set}}` – Creates a variable with the given name and value. It does not print anything to the template, so you must use `{{json}}` to print the value.
- `{{get}}` – Retrieves the value of a variable with the given name.
- `{{json}}` – Generates a JSON string from the given value; no need to use on strings.
- `{{concat}}` – Concatenates the given values into a string.

## Custom helpers
Lastly, you also have the following Handlebars helpers that you can use:

### `{{Writer-Acronym}}`
Description: Generate an acronym for the given concept or phrase
Inputs:
Output: string

### `{{Writer-AcronymGenerator}}`
Description: Given a request to generate an acronym from a string, generate an acronym and provide the acronym explanation.
Inputs:
Output: string

### `{{Writer-AcronymReverse}}`
Description: Given a single word or acronym, generate the expanded form matching the acronym letters.
Inputs:
Output: string

### `{{Writer-Brainstorm}}`
Description: Given a goal or topic description generate a list of ideas
Inputs:
Output: string

### `{{Writer-EmailGen}}`
Description: Write an email from the given bullet points
Inputs:
Output: string

### `{{Writer-EmailTo}}`
Description: Turn bullet points into an email to someone, using a polite tone
Inputs:
Output: string

### `{{Writer-EnglishImprover}}`
Description: Translate text to English and improve it
Inputs:
Output: string

### `{{Writer-NovelChapter}}`
Description: Write a chapter of a novel.
Inputs:
Output: string

### `{{Writer-NovelChapterWithNotes}}`
Description: Write a chapter of a novel using notes about the chapter to write.
Inputs:
Output: string

### `{{Writer-NovelOutline}}`
Description: Generate a list of chapter synopsis for a novel or novella
Inputs:
Output: string

### `{{Writer-Rewrite}}`
Description: Automatically generate compact notes for any text or text document
Inputs:
Output: string

### `{{Writer-ShortPoem}}`
Description: Turn a scenario into a short and entertaining poem.
Inputs:
Output: string

### `{{Writer-StoryGen}}`
Description: Generate a list of synopsis for a novel or novella with sub-chapters
Inputs:
Output: string

### `{{Writer-TellMeMore}}`
Description: Summarize given text or any text document
Inputs:
Output: string

### `{{Writer-Translate}}`
Description: Translate the input into a language of your choice
Inputs:
Output: string

### `{{Writer-TwoSentenceSummary}}`
Description: Summarize given text in two sentences or less
Inputs:
Output: string

IMPORTANT: You can only use the helpers that are listed above. Do not use any other helpers that are not listed here. For example, do not use `{{log}}` or any `{{Example}}` helpers, as they are not supported.</user~>
<system~>## Tips and tricks
- Add a comment above each step to describe what the step does.
- Use the `{{set}}` and `{{get}}` helpers to save and retrieve the results of another helper so you can use it later in the template without wasting resources.
- There are no initial variables available to you. You must create them yourself using the `{{set}}` helper and then access them using `{{get}}`.
- Do not make up values. Use the helpers to generate the data you need or extract it from the goal.
- Keep data well-defined. Each variable should have a unique name. Create and assign each variable only once.
- Be extremely careful about types. For example, if you pass an array to a helper that expects a number, the template will error out.
- Avoid using loops. Try a solution without before you deploy a loop.
- There is no need to check your results in the template.
- Do not nest sub-expressions or helpers because it will cause the template to error out.
- Each step should contain only one helper call.

## Start
Now take a deep breath and accomplish the task:
1. Keep the template short and sweet. Be as efficient as possible.
2. Do not use helpers or functions that were not provided to you, and be especially careful to not assume or make up any helpers or operations that were not explicitly defined already.
3. If none of the available helpers can achieve the goal, respond with "Additional helpers may be required".
4. The first steps should always be to initialize any variables you need.
5. The template should use the {{json}} helper at least once to output the result of the final step.
6. Don't forget to use the tips and tricks otherwise the template will not work.
7. Don't close the ``` handlebars block until you're done with all the steps.</system~>

**Comment by MikeYeager** [comment]
I also tried it with the gpt-35-turbo model and got a different exception: 
HandlebarsDotNet.HandlebarsCompilerException: 'An unhandled exception occurred while trying to compile the template'

The inner exception is 
'Sub-expression does not contain a converted MethodCall expression'

and the call stack of the inner exception is:
   at HandlebarsDotNet.Compiler.SubExpressionVisitor.VisitSubExpression(SubExpressionExpression subex)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Reduce(Expression expression, CompilationContext context, IReadOnlyList`1& decorators)
   at HandlebarsDotNet.Compiler.FunctionBinderHelpers.<>c__DisplayClass2_0.<CreateArguments>b__1(Expression o)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at HandlebarsDotNet.Compiler.FunctionBinderHelpers.CreateArguments(IEnumerable`1 expressions, CompilationContext compilationContext)
   at HandlebarsDotNet.Compiler.HelperFunctionBinder.VisitHelperExpression(HelperExpression hex)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at HandlebarsDotNet.Compiler.HelperFunctionBinder.VisitStatementExpression(StatementExpression sex)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at HandlebarsDotNet.Compiler.HandlebarsExpressionVisitor.Visit(Expression exp)
   at HandlebarsDotNet.Compiler.FunctionBuilder.Reduce(Expression expression, CompilationContext context, IReadOnlyList`1& decorators)
   at HandlebarsDotNet.Compiler.FunctionBuilder.CreateExpression(IEnumerable`1 expressions, CompilationContext compilationContext, IReadOnlyList`1& decorators)
 
That Prompt is:
<system~>## Instructions
Explain how to achieve the user's goal with the available helpers with a Handlebars template.

## Example
If the user wanted you to generate 10 random numbers and use them in another helper, you could answer with the following.</system~>
<user~>Please show me how to write a Handlebars template that achieves the following goal.

## Goal
I want you to generate 10 random numbers and send them to another helper.
</user~>
<assistant~>Here's the Handlebars template that achieves the goal:
```handlebars
{{!-- Step 1: Initialize the count --}}
{{set
  "count"
  10
}}
{{!-- Step 2: Loop using the count --}}
{{#each
  (range
    1
    (get
      "count"
    )
  )
}}
  {{set
    "index"
    this
  }}
  {{!-- Step 3: Create random number --}}
  {{set
    "randomNumber"
    (Example-Random
      seed=(get
        "index"
      )
    )
  }}
  {{!-- Step 4: Call example helper with random number and print the result to the screen --}}
  {{json
    (Example-Helper
      input=(get
        "randomNumber"
      )
    )
  }}
{{/each}}
```</assistant~>
<system~>Now let's try the real thing.</system~>
<user~>Please show me how to write a Handlebars template that achieves the following goal with the available helpers.

## Goal
Tomorrow is Valentine's day. I need to come up with a few date ideas. My significant other likes poems so write them in the form of a poem.

## Out-of-the-box helpers
The following helpers are available to you:
- `{{#if}}{{/if}}`
- `{{#unless}}{{/unless}}`
- `{{#each}}{{/each}}`
- `{{#with}}{{/with}}`

## Loop helpers
If you need to loop through a list of values with `{{#each}}`, you can use the following helpers:
- `{{range}}` – Generates a sequence of integral numbers within a specified range, inclusive of last value.
- `{{array}}` – Generates an array of values from the given values.

IMPORTANT: `range` and `array` are the only supported data structures. Others like `hash` are not supported. Also, you cannot use any methods or properties on the built-in data structures, such as `array.push` or `range.length`.

## Math helpers
If you need to do basic operations, you can use these two helpers with numerical values:
- `{{add}}` – Adds two values together.
- `{{subtract}}` – Subtracts the second value from the first.

## Comparison helpers
If you need to compare two values, you can use the `{{equal}}` helper.
To use the math and comparison helpers, you must pass in two positional values. For example, to check if the variable `var` is equal to number `1`, you would use the following helper like so: `{{#if (equal var 1)}}{{/if}}`.

## Variable helpers
If you need to create or retrieve a variable, you can use the following helpers:
- `{{set}}` – Creates a variable with the given name and value. It does not print anything to the template, so you must use `{{json}}` to print the value.
- `{{get}}` – Retrieves the value of a variable with the given name.
- `{{json}}` – Generates a JSON string from the given value; no need to use on strings.
- `{{concat}}` – Concatenates the given values into a string.

## Custom helpers
Lastly, you also have the following Handlebars helpers that you can use:

### `{{Writer-Acronym}}`
Description: Generate an acronym for the given concept or phrase
Inputs:
Output: string

### `{{Writer-AcronymGenerator}}`
Description: Given a request to generate an acronym from a string, generate an acronym and provide the acronym explanation.
Inputs:
Output: string

### `{{Writer-AcronymReverse}}`
Description: Given a single word or acronym, generate the expanded form matching the acronym letters.
Inputs:
Output: string

### `{{Writer-Brainstorm}}`
Description: Given a goal or topic description generate a list of ideas
Inputs:
Output: string

### `{{Writer-EmailGen}}`
Description: Write an email from the given bullet points
Inputs:
Output: string

### `{{Writer-EmailTo}}`
Description: Turn bullet points into an email to someone, using a polite tone
Inputs:
Output: string

### `{{Writer-EnglishImprover}}`
Description: Translate text to English and improve it
Inputs:
Output: string

### `{{Writer-NovelChapter}}`
Description: Write a chapter of a novel.
Inputs:
Output: string

### `{{Writer-NovelChapterWithNotes}}`
Description: Write a chapter of a novel using notes about the chapter to write.
Inputs:
Output: string

### `{{Writer-NovelOutline}}`
Description: Generate a list of chapter synopsis for a novel or novella
Inputs:
Output: string

### `{{Writer-Rewrite}}`
Description: Automatically generate compact notes for any text or text document
Inputs:
Output: string

### `{{Writer-ShortPoem}}`
Description: Turn a scenario into a short and entertaining poem.
Inputs:
Output: string

### `{{Writer-StoryGen}}`
Description: Generate a list of synopsis for a novel or novella with sub-chapters
Inputs:
Output: string

### `{{Writer-TellMeMore}}`
Description: Summarize given text or any text document
Inputs:
Output: string

### `{{Writer-Translate}}`
Description: Translate the input into a language of your choice
Inputs:
Output: string

### `{{Writer-TwoSentenceSummary}}`
Description: Summarize given text in two sentences or less
Inputs:
Output: string

IMPORTANT: You can only use the helpers that are listed above. Do not use any other helpers that are not listed here. For example, do not use `{{log}}` or any `{{Example}}` helpers, as they are not supported.</user~>
<system~>## Tips and tricks
- Add a comment above each step to describe what the step does.
- Use the `{{set}}` and `{{get}}` helpers to save and retrieve the results of another helper so you can use it later in the template without wasting resources.
- There are no initial variables available to you. You must create them yourself using the `{{set}}` helper and then access them using `{{get}}`.
- Do not make up values. Use the helpers to generate the data you need or extract it from the goal.
- Keep data well-defined. Each variable should have a unique name. Create and assign each variable only once.
- Be extremely careful about types. For example, if you pass an array to a helper that expects a number, the template will error out.
- Avoid using loops. Try a solution without before you deploy a loop.
- There is no need to check your results in the template.
- Do not nest sub-expressions or helpers because it will cause the template to error out.
- Each step should contain only one helper call.

## Start
Now take a deep breath and accomplish the task:
1. Keep the template short and sweet. Be as efficient as possible.
2. Do not use helpers or functions that were not provided to you, and be especially careful to not assume or make up any helpers or operations that were not explicitly defined already.
3. If none of the available helpers can achieve the goal, respond with "Additional helpers may be required".
4. The first steps should always be to initialize any variables you need.
5. The template should use the {{json}} helper at least once to output the result of the final step.
6. Don't forget to use the tips and tricks otherwise the template will not work.
7. Don't close the ``` handlebars block until you're done with all the steps.</system~>

**Comment by sanchez** [comment]
Sorry I'm not really familiar with the prompt style way of using SK but it does look like all your functions don't have inputs associated with them which might explain the error. Just checking, in the directory where you have your functions do you also have the correctly named json files and have you specified the input field inside that?

**Comment by MikeYeager** [comment]
@sanchez Hi Daniel. I'm using the Plugin samples from the SK repo. For example, here is the config.json that accompanies the Brainstorm prompt:
```
{
  "schema": 1,
  "type": "completion",
  "description": "Given a goal or topic description generate a list of ideas",
  "completion": {
    "max_tokens": 2000,
    "temperature": 0.5,
    "top_p": 1.0,
    "presence_penalty": 0.0,
    "frequency_penalty": 0.0,
    "stop_sequences": ["##END##"]
  },
  "input": {
    "parameters": [
      {
        "name": "input",
        "description": "A topic description or goal.",
        "defaultValue": ""
      }
    ]
  }
}
```

I've attached a zip file with all of the writer plugins including both prompts and settings.
[WriterPlugins.zip](https://github.com/microsoft/semantic-kernel/files/13666518/WriterPlugins.zip)

**Comment by MikeYeager** [comment]
New information. I just updated from RC-3 to RC-4 and the problem seems to be resolved. It doesn't complete the task very well at all with gpt-35-turbo, but it doesn't crash. It does work with gpt-4, but it's very slow and the quality of the results varies greatly. It's progress and the bug is fixed.

**Comment by teresaqhoang** [comment]
Thanks for calling this out @MikeYeager. Yeah, the planner is known to work better with gpt-4, but I'll definitely note this issue as another scenario for our testing. 

I'm also currently testing how the Handlebars Template Factory handles positional arguments + some optimizations for latency. Keep an eye out on our PRs for improvements!

**Comment by teresaqhoang** [comment]
> Thanks for calling this out @MikeYeager. Yeah, the planner is known to work better with gpt-4, but I'll definitely note this issue as another scenario for our testing.
> 
> I'm also currently testing how the Handlebars Template Factory handles positional arguments + some optimizations for latency. Keep an eye out on our PRs for improvements!

Closing as resolved. Will work on planner quality improvement separately.
