### ISSUE TITLE
.Net: HandlebarsPlanner  Exception of type 'System.StackOverflowException' was thrown.

### ISSUE THREAD

**Issue by strikene** [microsoft/semantic-kernel#4226]
**Describe the bug**
Using the handlebar to create a schedule throws an exception 

**To Reproduce**
KernelBuilder builder = new();
builder.Services.AddAzureOpenAIChatCompletion(
    deploymentName: "xxx",
    endpoint: "https://xxx.openai.azure.com/",
    apiKey: "xxxx",
    serviceId: OpenAIUseType.ChatCompletion.ToString(),
    modelId: "GPT-4"
    );
     builder.Plugins.AddFromObject(new HttpPlugin(), nameof(HttpPlugin));
     builder.Plugins.AddFromObject(new TextPlugin(), nameof(TextPlugin));
      builder.Plugins.AddFromObject(new TimePlugin(), nameof(TimePlugin));
      builder.Plugins.AddFromObject(new WaitPlugin(), nameof(WaitPlugin));
      builder.Plugins.AddFromObject(new ConversationSummaryPlugin(), nameof(ConversationSummaryPlugin));

HandlebarsPlanner HBP = new(new HandlebarsPlannerConfig(){AllowLoops = true,});
            HandlebarsPlan p1 = await HBP.CreatePlanAsync(kernel, "Summary page: https://www.bing.com/");

**Error info**
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.AddNestedComplexTypes(System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Reflection.PropertyInfo[])
   at Microsoft.SemanticKernel.Planning.Handlebars.KernelParameterMetadataExtensions.ToHandlebarsParameterTypeMetadata(System.Type)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner.SetComplexTypeDefinition(Microsoft.SemanticKernel.KernelParameterMetadata, System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata>, System.Collections.Generic.Dictionary`2<System.String,System.String>)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner.GetAvailableFunctionsManual(Microsoft.SemanticKernel.Kernel, System.Collections.Generic.HashSet`1<Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsParameterTypeMetadata> ByRef, System.Collections.Generic.Dictionary`2<System.String,System.String> ByRef, System.Threading.CancellationToken)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner+<CreatePlanCoreAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner+<CreatePlanCoreAsync>d__3, Microsoft.SemanticKernel.Planners.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3]](<CreatePlanCoreAsync>d__3 ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner+<CreatePlanCoreAsync>d__3, Microsoft.SemanticKernel.Planners.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3]](<CreatePlanCoreAsync>d__3 ByRef)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner.CreatePlanCoreAsync(Microsoft.SemanticKernel.Kernel, System.String, System.Threading.CancellationToken)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner+<>c.<CreatePlanAsync>b__2_0(Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner, Microsoft.SemanticKernel.Kernel, System.String, System.Threading.CancellationToken)
   at Microsoft.SemanticKernel.Planning.PlannerInstrumentation+<CreatePlanAsync>d__3`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[Microsoft.SemanticKernel.Planning.PlannerInstrumentation+<CreatePlanAsync>d__3`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.SemanticKernel.Planners.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3]](<CreatePlanAsync>d__3`2<System.__Canon,System.__Canon> ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[Microsoft.SemanticKernel.Planning.PlannerInstrumentation+<CreatePlanAsync>d__3`2[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Microsoft.SemanticKernel.Planners.Handlebars, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3]](<CreatePlanAsync>d__3`2<System.__Canon,System.__Canon> ByRef)
   at Microsoft.SemanticKernel.Planning.PlannerInstrumentation.CreatePlanAsync[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Func`5<System.__Canon,Microsoft.SemanticKernel.Kernel,System.String,System.Threading.CancellationToken,System.Threading.Tasks.Task`1<System.__Canon>>, System.__Canon, Microsoft.SemanticKernel.Kernel, System.String, Microsoft.Extensions.Logging.ILogger, System.Threading.CancellationToken)
   at Microsoft.SemanticKernel.Planning.Handlebars.HandlebarsPlanner.CreatePlanAsync(Microsoft.SemanticKernel.Kernel, System.String, System.Threading.CancellationToken)
   at ConsoleChatMSSKV2.Program+<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)

**Platform**
 - OS:  Windows
 - IDE:  Visual Studio
 - Language: C#
 - .net Version 7.0
 - Source: Microsoft.SemanticKernel.Planners.Handlebars 1.0.0-rc3

**Comment by teresaqhoang** [comment]
Will take a look at this today!

**Comment by dmm-l-mediehus** [comment]
I'm also getting this error in RC4. It happens when I add kernel memory plugin to kernel:
```
// Kernel Memory service
MemoryWebClient memory = new("https://localhost:7261/", "<APIKey>", "Authorization");
kernel.ImportPluginFromObject(new MemoryPlugin(memory));
```
And use 
```
HandlebarsPlanner planner = new();
HandlebarsPlan plan = await planner.CreatePlanAsync(kernel, input);
```

**Comment by peter-villadsen** [comment]
Is there an estimate for when this will be fixed? AFAIK, there are no other supported planners, so this is a denial of service, unless there is a workaround?

**Comment by teresaqhoang** [comment]
Hey @strikene, @dmm-l-mediehus, @peter-villadsen , this should've been fixed with this PR: https://github.com/microsoft/semantic-kernel/pull/4344 

Closing this issue, please re-open if you're still seeing the error with SK V1
