### ISSUE TITLE
.Net: RC4 breaks some example

### ISSUE THREAD

**Issue by alkampfergit** [microsoft/semantic-kernel#4304]
**Error trying to run a chat**

From previous example of RC3 I have this simple code that simulate usage of a chat model 

   ```csharp
 public static async Task Ex02_b_InvokeLLMDirectly()
    {
        var builder = CreateBasicKernelBuilder();
        var kernel = builder.Build();

        var chatPrompt = Path.Combine(
            Directory.GetCurrentDirectory(),
            "Prompts",
            "chat.yaml");
        var promptContent = File.ReadAllText(chatPrompt);
        KernelFunction prompt = kernel.CreateFunctionFromPromptYaml(
            promptContent,
            promptTemplateFactory: new HandlebarsPromptTemplateFactory()
        );

        ChatHistory chatMessages = new();
        chatMessages.AddUserMessage("Hi what is your name?");
        chatMessages.AddAssistantMessage("I am an Assistant ai but you can call me Jarvis");
        chatMessages.AddUserMessage("My name is Gian Maria");
        chatMessages.AddAssistantMessage("Hi Gian Maria how can I help you?");
        chatMessages.AddUserMessage("Tell my name and repeat how can I call you!");
        var result = await kernel.InvokeAsync<string>(
            prompt,
            new KernelArguments()
            {
                ["messages"] = chatMessages
            });
        Console.WriteLine("Result: {0}", result);
    }
```

Now running the example in RC3 it works, with RC4 I got this internal error ... It seems that something is missing from Microsoft.SemanticKernel.Abstractions

```
 Function failed. Error: Could not load type 'Microsoft.SemanticKernel.IKernelPlugin' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.
      System.TypeLoadException: Could not load type 'Microsoft.SemanticKernel.IKernelPlugin' from assembly 'Microsoft.SemanticKernel.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.
         at Microsoft.SemanticKernel.PromptTemplate.Handlebars.HandlebarsPromptTemplate.RenderAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Microsoft.SemanticKernel.PromptTemplate.Handlebars.HandlebarsPromptTemplate.RenderAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunctionFromPrompt.RenderPromptAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
```

This package was not published in rc4. How it is possible? It is deprecated? It was a sample taken straigth from RC3 

![image](https://github.com/microsoft/semantic-kernel/assets/358545/83a53cf3-e4a8-42a7-9966-21e14e9f29e9)

**Comment by alkampfergit** [comment]
ACH it seems that the library is now called Microsoft.SemanticKernel.PromptTemplate**s**.Handlebars  with an s in PromptTemplates ... ufff...

**Comment by ckpearson** [comment]
I've just been bitten by this and it wasn't obvious what was causing it, is the previous package going to be removed / marked as deprecated? This could do with being called out in the docs.
