### ISSUE TITLE
.Net: The API deployment for this resource does not exist

### ISSUE THREAD

**Issue by hyunoosung** [microsoft/semantic-kernel#4464]
**Describe the bug**

```
Error: Microsoft.SemanticKernel.HttpOperationException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
Status: 404 (Not Found)
ErrorCode: DeploymentNotFound

Content:
{"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

Headers:
apim-request-id: REDACTED
x-ms-client-request-id: 843657a2-f43f-49da-a1f5-6ecc4206e71f
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
x-ms-region: REDACTED
Date: Wed, 03 Jan 2024 13:28:55 GMT
Content-Length: 198
Content-Type: application/json

---> Azure.RequestFailedException: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.
Status: 404 (Not Found)
ErrorCode: DeploymentNotFound

Content:
{"error":{"code":"DeploymentNotFound", "message":"The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again."}}

Headers:
apim-request-id: REDACTED
x-ms-client-request-id: 843657a2-f43f-49da-a1f5-6ecc4206e71f
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
x-ms-region: REDACTED
Date: Wed, 03 Jan 2024 13:28:55 GMT
Content-Length: 198
Content-Type: application/json

at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
at Azure.AI.OpenAI.OpenAIClient.GetImageGenerationsAsync(ImageGenerationOptions imageGenerationOptions, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAITextToImageService.GenerateImageAsync(String description, Int32 width, Int32 height, Kernel kernel, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at Microsoft.SemanticKernel.Connectors.OpenAI.AzureOpenAITextToImageService.GenerateImageAsync(String description, Int32 width, Int32 height, Kernel kernel, CancellationToken cancellationToken)
at Submission#10.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```
**To Reproduce**
1. Go to '07-DALL-E-3' on notebooks folder
2. Run  Generate a (random) image with DALL-E 3
3. See error

**Expected behavior**

A cure bear image is ecpected.

**Screenshots**

kernel is created succefuly
![image](https://github.com/microsoft/semantic-kernel/assets/9585318/66b045ea-8fc4-4fc3-a5d2-bad36621a480)

Generation gets error
![image](https://github.com/microsoft/semantic-kernel/assets/9585318/1b8ea253-6d76-4a79-bcd8-c1b563bfc5bc)

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: C#
 - Source: main branch of repository

**Additional context**

**Comment by hyunoosung** [comment]
When I follow below doc, it runs well
https://learn.microsoft.com/en-us/azure/ai-services/openai/dall-e-quickstart?tabs=dalle3%2Ccommand-line&pivots=programming-language-csharp
```cs
using System;
using System.IO;
using System.Threading.Tasks;
using Azure.AI.OpenAI;

namespace Azure.AI.OpenAI.Tests.Samples
{
    public partial class GenerateImages
    {
        // add an async Main method:
        public static async Task Main(string[] args)
        {
            string endpoint = GetEnvironmentVariable("AZURE_OPENAI_ENDPOINT");
            string key = GetEnvironmentVariable("AZURE_OPENAI_KEY");

            OpenAIClient client = new(new Uri(endpoint), new AzureKeyCredential(key));

            Response<ImageGenerations> imageGenerations = await client.GetImageGenerationsAsync(
                new ImageGenerationOptions()
                {
                    Prompt = "a happy monkey eating a banana, in watercolor",
                    Size = ImageSize.Size256x256,
                });

            // Image Generations responses provide URLs you can use to retrieve requested images
            Uri imageUri = imageGenerations.Value.Data[0].Url;
            
            // Print the image URI to console:
            Console.WriteLine(imageUri);
        }
    }
}
```

ImageGenerationOptions class taking not nullable DeploymentName and passing 'dall-e-3'  or any other model throws above exception.

**Comment by hyunoosung** [comment]
Confirmed that Azure.AI.OpenAI --version 1.0.0-beta.7 works but from beta.8 ~ 12 throws exception
