### ISSUE TITLE
.NET: FunctionCallingStepwisePlanner throwing error

### ISSUE THREAD

**Issue by gitri-ms** [microsoft/semantic-kernel#4586]
**Describe the bug**
From customer:
```
Since Last night, the planner in my service has stopped working without any code change. While I'm able to call "kernel.InvokeAsync" & HandlebarsPlanner and get the result, any call to FunctionCallingStepwisePlanner is not working. Planner call just hangs on for roughly 20-30 seconds and then throws an error. 
 
The call is fairly simple and was working since last few weeks:
result = await planner.ExecuteAsync(kernel, planPrompt);
 
Error:
Invalid value for 'content': expected a string, got null.
Status: 400 (model_error)
Content:
{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[12].content",
    "code": null
  }
}
 
at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
         at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
         --- End of inner exception stack trace ---
         at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
         at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Planning.FunctionCallingStepwisePlanner.GetCompletionWithFunctionsAsync(ChatHistory chatHistory, Kernel kernel, IChatCompletionService chatCompletion, OpenAIPromptExecutionSettings openAIExecutionSettings, ILogger logger, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.Planning.FunctionCallingStepwisePlanner.ExecuteCoreAsync(Kernel kernel, String question, CancellationToken cancellationToken)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: [e.g. Visual Studio, VS Code]
 - Language: C#
 - Source: [e.g. NuGet package version 0.1.0, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by gitri-ms** [comment]
Closing as duplicate of #4556
