### ISSUE TITLE
.Net: System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.

### ISSUE THREAD

**Issue by Alerinos** [microsoft/semantic-kernel#4594]
Error:
```
Microsoft.SemanticKernel.KernelFunctionCanceledException: The invocation of function 'GetIntent' was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
 ---> System.Net.Sockets.SocketException (125): Operation canceled
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, String prompt, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
   ```
   
 MyContext:
 ```cs
         var httpClient = new HttpClient
        {
            Timeout = TimeSpan.FromMinutes(10),
        };

        var builder = Kernel.CreateBuilder();

        builder.Services.ConfigureHttpClientDefaults(c =>
        {
            // Use a standard resiliency policy, augmented to retry on 401 Unauthorized, 502 Bad Gateway and on timeout for this example
            c.AddStandardResilienceHandler().Configure(o =>
            {
                // Combine checks for status codes and timeout into one delegate to set as the ShouldHandle policy
                o.Retry.ShouldHandle = args =>
                {
                    // Check if the response has a status code that we should handle
                    var isStatusCodeToRetry = args.Outcome.Result?.StatusCode is HttpStatusCode.Unauthorized
                                              || args.Outcome.Result?.StatusCode is HttpStatusCode.BadGateway;

                    // Check if the result was a timeout (typically when the result is null and an exception is a TaskCanceledException)
                    var isTimeout = args.Outcome.Exception?.InnerException is TaskCanceledException;

                    // Combine the checks
                    return ValueTask.FromResult(isStatusCodeToRetry || isTimeout);
                };
            });
        });

        builder.AddOpenAIChatCompletion("gpt-3.5-turbo-1106", token, httpClient: httpClient);
        builder.AddOpenAIChatCompletion("gpt-4-1106-preview", token, httpClient: httpClient);
        builder.AddOpenAIChatCompletion("gpt-4-vision-preview", token, httpClient: httpClient);

        return builder.Build();
```

Why does SK have a time out somewhere? I have version 1.0.1, why is it different in every version of SK? Why is there no documentation about it?  How can I increase the timeout?

**Comment by markwallace-microsoft** [comment]
@Alerinos SK uses the [Azure OpenAI client library for .NET](https://github.com/Azure/azure-sdk-for-net/tree/Azure.AI.OpenAI_1.0.0-beta.9/sdk/openai/Azure.AI.OpenAI). This defines the default timeout that is used in the [RetryOptions.cs](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.OpenAI_1.0.0-beta.9/sdk/core/Azure.Core/src/RetryOptions.cs). The [sample](https://github.com/microsoft/semantic-kernel/blob/main/dotnet/samples/KernelSyntaxExamples/Example52_ApimAuth.cs) shows how to pass in custom client options.

Some useful resources include:
- https://learn.microsoft.com/en-us/azure/ai-services/openai/reference
- https://learn.microsoft.com/en-us/azure/ai-services/openai/

**Comment by Alerinos** [comment]
@markwallace-microsoft 
I noticed that by increasing the time out in OpenAi he still does not respond. There is a problem with them, this problem has a lot of users. You can see by the number of requests, maybe you should make a built-in error system and retry in case of error?

**Comment by Alerinos** [comment]
@markwallace-microsoft 
I wanted to approach the topic again but the example does not exist.
From what I remember you gave an example for Azure, unfortunately, but I use OpenAI Api which was significantly different there.

![image](https://github.com/microsoft/semantic-kernel/assets/42449535/545a9e6a-29ec-4be0-b739-94f24a688731)

**Comment by Alerinos** [comment]
```cs
        var httpClient = new HttpClient
        {
            Timeout = TimeSpan.FromMinutes(10),
        };

        var clientOptions = new OpenAIClientOptions();
        clientOptions.Retry.MaxRetries = 3;
        clientOptions.Retry.NetworkTimeout = TimeSpan.FromMinutes(5);
        var openAIClient = new OpenAIClient(new Uri("https://api.openai.com"), new AzureKeyCredential(token), clientOptions);
```

Where do I get the endpoint from? Doesn't work with OPEN AI, doesn't want some azure.... I use OPEN AI.

No offense, but in its current state Semantic Kernel is a failure. It loses out on such basic features through lack of documentation and constant changes. I'm wasting hours on something where it could have been done in minutes via API.

**Comment by Alerinos** [comment]
I managed to find that you need to use something like this:
```cs
var openAIClient = new OpenAIClient($"{token}.openai.com", clientOptions);
```

unfortunately it keeps returning me an error.... 
```
Microsoft.SemanticKernel.HttpOperationException: Incorrect API key provided: sk-**************************************************.com. You can find your API key at https://platform.openai.com/account/api-keys.
Status: 401 (Unauthorized)
ErrorCode: invalid_api_key
```

**Comment by Alerinos** [comment]
@markwallace-microsoft I give up, two hours wasted. Doesn't want to work, no documentation and how to do it....
What I found on github does not work....

**Comment by Alerinos** [comment]
omg!
The documentation explains wrong, in the OpenAiClient patameter you only give the API KEY. According to the documentation you have to give the api key and then the open ai domain.
Why did someone describe it so poorly? Why does this function take such parameters? There should be two separate functions, separated and the parameter should clearly take a string token!
