### ISSUE TITLE
.Net: CompletionsUsage object throws null exception with gpt-4-32k (v0613)

### ISSUE THREAD

**Issue by mmckechney** [microsoft/semantic-kernel#4953]
**Describe the bug**
When using the gpt-4-32k (v0613) Azure OpenAI model, Semantic kernel throws a null reference exception at `Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.CaptureUsageDetails(CompletionsUsage usage)`

Switching the model to gpt-4 (v1106-Preview), the `usage` object is created and does have populated properties.

**To Reproduce**
1. Run a Semantic Kernel `InvokeAsync` against a function targeting the gpt-4-32k model. Mine was created by `CreateFunctionFromPromptYaml`, but this may not be relevant. 

**Expected behavior**
No exception is thrown 

**Screenshots**
The stack trace for the exception that is thrown is:
```
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.CaptureUsageDetails(CompletionsUsage usage)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetChatMessageContentsAsync>d__27.MoveNext()
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.<GetChatMessageContentAsync>d__1.MoveNext()
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeCoreAsync>d__3.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.SemanticKernel.KernelFunction.<InvokeAsync>d__18.MoveNext()
```
**Platform**
 - OS: Windows
 - IDE: Visual Studio
 - Language: C#
 - Source: SK NuGet packages version 1.3.0

**Additional context**

**Comment by pratibw** [comment]
Same error occurring for us as well: 

   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.CaptureUsageDetails(CompletionsUsage usage)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetChatMessageContentsAsync>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.<GetChatMessageContentAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeCoreAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SemanticKernel.KernelFunction.<InvokeAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Comms.Acm.Business.Services.SemanticKernelAdaptor.<GetContentUsingSemanticKernelForOutageSkill>d__4.MoveNext() 


Code: 

                KernelArguments kernelarguments = new KernelArguments { { "input", message } };

                return await kernel.InvokeAsync(function, kernelarguments);

And it says Object reference not set to a instance of an object. Enumeration yielded no result.

**Comment by dmytrostruk** [comment]
Unfortunately, I can't reproduce it. Looking at method implementation, there are 3 objects used:
- `usage`: maybe for some reason this information was removed from completion API, that's why this object is `null`.
- `Logger`: it's always initialized. In case it's not passed to `ClientCore`, `NullLogger` will be used instead.
- `Metering counters`: these objects are initialized on `ClientCore` initialization, and I don't think they are `null`. 

Taking into account, that most probably in this code `usage` object is null, I've added the PR that temporarily should fix this problem, until we figure out why this happened: https://github.com/microsoft/semantic-kernel/pull/4956

**Comment by rajanikanthr** [comment]
> Unfortunately, I can't reproduce it. Looking at method implementation, there are 3 objects used:
> 
> * `usage`: maybe for some reason this information was removed from completion API, that's why this object is `null`.
> * `Logger`: it's always initialized. In case it's not passed to `ClientCore`, `NullLogger` will be used instead.
> * `Metering counters`: these objects are initialized on `ClientCore` initialization, and I don't think they are `null`.
> 
> Taking into account, that most probably in this code `usage` object is null, I've added the PR that temporarily should fix this problem, until we figure out why this happened: #4956

we are also getting the same error from this morning, somehow it works with Azure OpenAI acoount-1 but fails with account-2.

screenshot from the debug, 
SK nuget version: 0.24.230911.2-preview
method: ClientBase.cs -> InternalGetChatResultsAsync
<img width="675" alt="image" src="https://github.com/microsoft/semantic-kernel/assets/1663830/437e8bee-fb57-4b58-af1d-04caa479ced0">

**Comment by dmytrostruk** [comment]
@rajanikanthr Thanks for confirming, based on your screenshot it looks like `Usage` is null and PR that I shared above should fix this problem.

**Comment by Patrickdlg** [comment]
This is breaking one of my applications at the moment. I've read the pull request - is there a workaround that I can use?

**Comment by Bhouben** [comment]
https://github.com/microsoft/semantic-kernel/issues/4953

**Comment by markwallace-microsoft** [comment]
New release (1.3.1) has been published https://www.nuget.org/packages/Microsoft.SemanticKernel.Connectors.OpenAI
