### ISSUE TITLE
Python: TypeError: can only concatenate str (not "NoneType") to str（BasicPlanner）

### ISSUE THREAD

**Issue by yuichiromukaiyama** [microsoft/semantic-kernel#5309]
**Describe the bug**
I encountered the following error when using BasicPlanner:
An example code is as follows:

**To Reproduce**

```python
import asyncio
from semantic_kernel.connectors.ai.open_ai import AzureChatCompletion
from semantic_kernel.planners.basic_planner import BasicPlanner
from semantic_kernel.kernel import Kernel
from semantic_kernel.core_plugins import MathPlugin

async def main():

    kernel = Kernel()

    kernel.add_service(
        AzureChatCompletion(
            service_id="chat_completion",
            deployment_name=AZURE_OPENAI_DEPLOYMENT_NAME,
            endpoint=AZURE_OPENAI_ENDPOINT,
            api_key=AZURE_OPENAI_API_KEY,
        )
    )

    kernel.import_plugin_from_object(
        plugin_instance=MathPlugin(),
        plugin_name="MathPlugin",
    )

    planner = BasicPlanner("chat_completion")
    plan = await planner.create_plan("1 + 1 =",kernel) # <- error
    print(plan.generated_plan)

asyncio.run(main())

```

```sh
Traceback (most recent call last):
  File "/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/.pyenv/versions/3.10.13/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/semantic-kernel-test/app/__main__.py", line 49, in <module>
    asyncio.run(main())
  File "/.pyenv/versions/3.10.13/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/semantic-kernel-test/app/__main__.py", line 37, in main
    plan = await planner.create_plan(
  File "/semantic-kernel-test/.venv/lib/python3.10/site-packages/semantic_kernel/planners/basic_planner.py", line 205, in create_plan
    available_functions_string = self._create_available_functions_string(kernel)
  File "/semantic-kernel-test/.venv/lib/python3.10/site-packages/semantic_kernel/planners/basic_planner.py", line 162, in _create_available_functions_string
    available_functions_string += "description: " + description + "\n"
TypeError: can only concatenate str (not "NoneType") to str
```

**Expected behavior**
BasicPlanner will create my plan.

**Platform**
 - OS: Mac
 - IDE: VS Code
 - Language: Python
 - Source:  Version: 0.9.0b1

**Additional context**
The problem is in the following location. description may include "None."

https://github.com/microsoft/semantic-kernel/blob/8deaaf4e8285695f78d34360e8c7433f7da1d862/python/semantic_kernel/planners/basic_planner.py#L155

```
available_functions_string += "description: " + description + "\n"
```

The one with no description specified is BasicPlanner.

https://github.com/microsoft/semantic-kernel/blob/8deaaf4e8285695f78d34360e8c7433f7da1d862/python/semantic_kernel/planners/basic_planner.py#L192

Below is the current code

```python
        planner = kernel.create_function_from_prompt(
            plugin_name="PlannerPlugin",
            function_name="CreatePlan",
            prompt_template_config=prompt_template_config,
        )
```

I think the correct answer is as follows. Also, the description probably needs some proper explanation.（Even if I just wrote "planner" in the description, it worked without any problems.）

```python
        planner = kernel.create_function_from_prompt(
            plugin_name="PlannerPlugin",
            function_name="CreatePlan",
            description="????some description????",
            prompt_template_config=prompt_template_config,
        )
```

**Comment by MaxiPigna** [comment]
Same issue when importing plugin in this way
```
self.kernel.import_plugin_from_prompt_directory("plugins", "orchestrator")
self.planner = BasicPlanner(self.service_id)
```

**Comment by WanlinLi2021** [comment]
Same issue in `python/notebooks/05-using-the-planner.ipynb`
