### ISSUE TITLE
.Net: OpenAPI function calling fails for `me/microsoft.graph.sendMail` endpoint of Microsoft Graph

### ISSUE THREAD

**Issue by zengin** [microsoft/semantic-kernel#5384]
**Describe the bug**
An exception is thrown while creating a message object for sendMail endpoint of Microsoft.Graph.

It happens when an APIManifest based OpenAPI plugin is generated for `me/microsoft.graph.sendMail` endpoint and the goal "Send email to user@contoso.com with subject:A and body:B" is executed with function calling stepwise planner.

The repro steps may be isolated further to call the generated SK OpenAPI function directly, but I am leaving the planner repro as is in case it sets function parameters in an unexpected fashion.

Please note that auth setup for Graph is not needed for this repro.

**To Reproduce**
1. Create a new file: `dotnet/samples/KernelSyntaxExamples/Plugins/ApiManifestPlugins/SendMailPlugin/apimanifest.json` with following contents:
```json
{
    "applicationName": "SemanticKernel",
    "publisher": {
        "name": "publisher-name",
        "contactEmail": "publisher-email@example.com"
    },
    "apiDependencies": {
        "microsoft.graph": {
            "apiDescriptionUrl": "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/graphexplorer.yaml",
            "requests": [
                {
                    "method": "Post",
                    "uriTemplate": "/me/microsoft.graph.sendMail"
                }
            ]
        }
    }
}
```
2. Create a new file `dotnet/samples/KernelSyntaxExamples/Example_SendMail.cs` with following contents, make sure to add your function calling AI service details:
```csharp
// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Planning;
using Microsoft.SemanticKernel.Plugins.OpenApi;
using Microsoft.SemanticKernel.Plugins.OpenApi.Extensions;
using Xunit;
using Xunit.Abstractions;
namespace Examples;

public class Example_SendMail : BaseTest
{
    public Example_SendMail(ITestOutputHelper output) : base(output)
    {
    }

    [Fact]
    public async Task RunAsync()
    {
        var builder = Kernel.CreateBuilder();
        builder.Services.AddLogging(loggingBuilder =>
        {
            loggingBuilder.AddFilter(level => true);
            loggingBuilder.AddConsole();
        });
        var kernel = builder.AddAzureOpenAIChatCompletion(
                deploymentName: "<YOUR_DEPLOYMENT_NAME>",
                endpoint: "<YOUR_ENDPOINT",
                serviceId: "AzureOpenAIChat",
                apiKey: "<YOUR_API_KEY>",
                modelId: "<YOUR_MODEL_ID>").Build();
        await AddApiManifestPluginsAsync(kernel, "SendMailPlugin");
        FunctionCallingStepwisePlannerOptions plannerConfig = new()
        {
            MaxIterations = 15,
            MaxTokens = 32000
        };
        var planner = new FunctionCallingStepwisePlanner(plannerConfig);
        var result = await planner.ExecuteAsync(kernel, "Send email to user@contoso.com with subject:A and body:B");
        this.WriteLine("--------------------");
        this.WriteLine($"\nResult:\n{result.FinalAnswer}\n");
        this.WriteLine("--------------------");
    }

    private async Task AddApiManifestPluginsAsync(Kernel kernel, params string[] pluginNames)
    {
        foreach (var pluginName in pluginNames)
        {
            try
            {
#pragma warning disable SKEXP0042
#pragma warning disable SKEXP0043
                KernelPlugin plugin =
                await kernel.ImportPluginFromApiManifestAsync(
                    pluginName,
                    $"Plugins/ApiManifestPlugins/{pluginName}/apimanifest.json",
                    new OpenApiFunctionExecutionParameters(serverUrlOverride: new Uri("https://graph.microsoft.com/v1.0")))
                    .ConfigureAwait(false);
                this.WriteLine($">> {pluginName} is created.");
#pragma warning restore SKEXP0042
#pragma warning restore SKEXP0043
            }
            catch (Exception ex)
            {
                kernel.LoggerFactory.CreateLogger("Plugin Creation").LogError(ex, "Plugin creation failed. Message: {0}", ex.Message);
                throw new AggregateException($"Plugin creation failed for {pluginName}", ex);
            }
        }
    }
}

```
3. `cd dotnet/samples/KernelSyntaxExamples`
4. `dotnet build`
5. `dotnet test KernelSyntaxExamples.csproj --filter Example_SendMail --logger "console;verbosity=detailed"`
6. See the following error
```
trce: Mesendmail[0]
      Function arguments: {"Message":"{\n    \u0022toRecipients\u0022: [\n      {\n        \u0022emailAddress\u0022: {\n          \u0022address\u0022: \u0022user@contoso.com\u0022,\n          \u0022name\u0022: \u0022\u0022\n        }\n      }\n    ],\n    \u0022subject\u0022: \u0022A\u0022,\n    \u0022body\u0022: {\n      \u0022content\u0022: \u0022B\u0022,\n      \u0022contentType\u0022: \u0022text\u0022\n    }\n  }","SaveToSentItems":"False"}
fail: Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions[0]
      RestAPI function SendMailPlugin.me.sendMail execution failed with error Unexpected type '' of parameter 'Message' with argument '{
          "toRecipients": [
            {
              "emailAddress": {
                "address": "user@contoso.com",
                "name": ""
              }
            }
          ],
          "subject": "A",
          "body": {
            "content": "B",
            "contentType": "text"
          }
        }'.
      System.NotSupportedException: Unexpected type '' of parameter 'Message' with argument '{
          "toRecipients": [
            {
              "emailAddress": {
                "address": "user@contoso.com",
                "name": ""
              }
            }
          ],
          "subject": "A",
          "body": {
            "content": "B",
            "contentType": "text"
          }
        }'.
         at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiTypeConverter.Convert(String name, String type, Object argument) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/Serialization/OpenApiTypeConverter.cs:line 55
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildJsonObject(IList`1 properties, IDictionary`2 arguments, String propertyNamespace) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 307
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildJsonPayload(RestApiOperationPayload payloadMetadata, IDictionary`2 arguments) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 269
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildOperationPayload(RestApiOperation operation, IDictionary`2 arguments) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 250
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.RunAsync(RestApiOperation operation, KernelArguments arguments, RestApiOperationRunOptions options, CancellationToken cancellationToken) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 129
         at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.<>c__DisplayClass7_0.<<CreateRestApiFunction>g__ExecuteAsync|0>d.MoveNext() in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiKernelExtensions.cs:line 314
fail: Mesendmail[0]
      Function failed. Error: Unexpected type '' of parameter 'Message' with argument '{
          "toRecipients": [
            {
              "emailAddress": {
                "address": "user@contoso.com",
                "name": ""
              }
            }
          ],
          "subject": "A",
          "body": {
            "content": "B",
            "contentType": "text"
          }
        }'.
      System.NotSupportedException: Unexpected type '' of parameter 'Message' with argument '{
          "toRecipients": [
            {
              "emailAddress": {
                "address": "user@contoso.com",
                "name": ""
              }
            }
          ],
          "subject": "A",
          "body": {
            "content": "B",
            "contentType": "text"
          }
        }'.
         at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiTypeConverter.Convert(String name, String type, Object argument) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/Serialization/OpenApiTypeConverter.cs:line 55
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildJsonObject(IList`1 properties, IDictionary`2 arguments, String propertyNamespace) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 307
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildJsonPayload(RestApiOperationPayload payloadMetadata, IDictionary`2 arguments) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 269
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.BuildOperationPayload(RestApiOperation operation, IDictionary`2 arguments) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 250
         at Microsoft.SemanticKernel.Plugins.OpenApi.RestApiOperationRunner.RunAsync(RestApiOperation operation, KernelArguments arguments, RestApiOperationRunOptions options, CancellationToken cancellationToken) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/RestApiOperationRunner.cs:line 129
         at Microsoft.SemanticKernel.Plugins.OpenApi.OpenApiKernelExtensions.<>c__DisplayClass7_0.<<CreateRestApiFunction>g__ExecuteAsync|0>d.MoveNext() in /Users/mustafazengin/g/semantic-kernel/dotnet/src/Functions/Functions.OpenApi/Extensions/OpenApiKernelExtensions.cs:line 314
      --- End of stack trace from previous location ---
         at Microsoft.SemanticKernel.KernelFunctionFromMethod.<>c__DisplayClass13_0.<<GetReturnValueMarshalerDelegate>b__10>d.MoveNext() in /Users/mustafazengin/g/semantic-kernel/dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromMethod.cs:line 569
      --- End of stack trace from previous location ---
         at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken) in /Users/mustafazengin/g/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs:line 164
```

**Expected behavior**
Message type is not empty.

**Additional context**
<details>

<summary>
Expand to see the YAML serialization of sliced OpenAPI document
</summary>

```yaml
openapi: 3.0.1
info:
  title: OData Service for namespace microsoft.graph - Subset
  description: This OData service is located at https://graph.microsoft.com/v1.0
  version: v1.0
  x-ms-generated-by:
    toolName: Microsoft.OpenApi.OData
    toolVersion: 1.0.9.0
servers:
  - url: https://graph.microsoft.com/v1.0
paths:
  /me/microsoft.graph.sendMail:
    post:
      tags:
        - me.Actions
      summary: Invoke action sendMail
      description: 'Send the message specified in the request body using either JSON or MIME format. When using JSON format, you can include a file attachment in the same sendMail action call. When using MIME format: This method saves the message in the Sent Items folder. Alternatively, create a draft message to send later. To learn more about the steps involved in the backend before a mail is delivered to recipients, see here.'
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/user-sendmail?view=graph-rest-1.0
      operationId: me.sendMail
      requestBody:
        description: Action parameters
        content:
          application/json:
            schema:
              type: object
              properties:
                Message:
                  allOf:
                    - allOf:
                        - title: entity
                          type: object
                          properties:
                            id:
                              type: string
                              description: The unique identifier for an entity. Read-only.
                        - title: outlookItem
                          type: object
                          properties:
                            categories:
                              type: array
                              items:
                                type: string
                                nullable: true
                              description: The categories associated with the item
                            changeKey:
                              type: string
                              description: 'Identifies the version of the item. Every time the item is changed, changeKey changes as well. This allows Exchange to apply changes to the correct version of the object. Read-only.'
                              nullable: true
                            createdDateTime:
                              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                              type: string
                              description: 'The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z'
                              format: date-time
                              nullable: true
                            lastModifiedDateTime:
                              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                              type: string
                              description: 'The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z'
                              format: date-time
                              nullable: true
                    - title: message
                      type: object
                      properties:
                        bccRecipients:
                          type: array
                          items:
                            title: recipient
                            type: object
                            properties:
                              emailAddress:
                                anyOf:
                                  - title: emailAddress
                                    type: object
                                    properties:
                                      address:
                                        type: string
                                        description: The email address of the person or entity.
                                        nullable: true
                                      name:
                                        type: string
                                        description: The display name of the person or entity.
                                        nullable: true
                                  - type: object
                                    nullable: true
                                description: The recipient's email address.
                          description: 'The Bcc: recipients for the message.'
                        body:
                          anyOf:
                            - title: itemBody
                              type: object
                              properties:
                                content:
                                  type: string
                                  description: The content of the item.
                                  nullable: true
                                contentType:
                                  anyOf:
                                    - title: bodyType
                                      enum:
                                        - text
                                        - html
                                      type: string
                                    - type: object
                                      nullable: true
                                  description: The type of the content. Possible values are text and html.
                            - type: object
                              nullable: true
                          description: The body of the message. It can be in HTML or text format. Find out about safe HTML in a message body.
                        bodyPreview:
                          type: string
                          description: The first 255 characters of the message body. It is in text format.
                          nullable: true
                        ccRecipients:
                          type: array
                          items:
                            title: recipient
                            type: object
                            properties:
                              emailAddress:
                                anyOf:
                                  - title: emailAddress
                                    type: object
                                    properties:
                                      address:
                                        type: string
                                        description: The email address of the person or entity.
                                        nullable: true
                                      name:
                                        type: string
                                        description: The display name of the person or entity.
                                        nullable: true
                                  - type: object
                                    nullable: true
                                description: The recipient's email address.
                          description: 'The Cc: recipients for the message.'
                        conversationId:
                          type: string
                          description: The ID of the conversation the email belongs to.
                          nullable: true
                        conversationIndex:
                          type: string
                          description: Indicates the position of the message within the conversation.
                          format: base64url
                          nullable: true
                        flag:
                          anyOf:
                            - title: followupFlag
                              type: object
                              properties:
                                completedDateTime:
                                  anyOf:
                                    - title: dateTimeTimeZone
                                      type: object
                                      properties:
                                        dateTime:
                                          type: string
                                          description: 'A single point of time in a combined date and time representation ({date}T{time}; for example, 2017-08-29T04:00:00.0000000).'
                                        timeZone:
                                          type: string
                                          description: 'Represents a time zone, for example, ''Pacific Standard Time''. See below for more possible values.'
                                          nullable: true
                                    - type: object
                                      nullable: true
                                  description: The date and time that the follow-up was finished.
                                dueDateTime:
                                  anyOf:
                                    - title: dateTimeTimeZone
                                      type: object
                                      properties:
                                        dateTime:
                                          type: string
                                          description: 'A single point of time in a combined date and time representation ({date}T{time}; for example, 2017-08-29T04:00:00.0000000).'
                                        timeZone:
                                          type: string
                                          description: 'Represents a time zone, for example, ''Pacific Standard Time''. See below for more possible values.'
                                          nullable: true
                                    - type: object
                                      nullable: true
                                  description: 'The date and time that the follow-up is to be finished. Note: To set the due date, you must also specify the startDateTime; otherwise, you get a 400 Bad Request response.'
                                flagStatus:
                                  anyOf:
                                    - title: followupFlagStatus
                                      enum:
                                        - notFlagged
                                        - complete
                                        - flagged
                                      type: string
                                    - type: object
                                      nullable: true
                                  description: 'The status for follow-up for an item. Possible values are notFlagged, complete, and flagged.'
                                startDateTime:
                                  anyOf:
                                    - title: dateTimeTimeZone
                                      type: object
                                      properties:
                                        dateTime:
                                          type: string
                                          description: 'A single point of time in a combined date and time representation ({date}T{time}; for example, 2017-08-29T04:00:00.0000000).'
                                        timeZone:
                                          type: string
                                          description: 'Represents a time zone, for example, ''Pacific Standard Time''. See below for more possible values.'
                                          nullable: true
                                    - type: object
                                      nullable: true
                                  description: The date and time that the follow-up is to begin.
                            - type: object
                              nullable: true
                          description: 'The flag value that indicates the status, start date, due date, or completion date for the message.'
                        from:
                          anyOf:
                            - title: recipient
                              type: object
                              properties:
                                emailAddress:
                                  anyOf:
                                    - title: emailAddress
                                      type: object
                                      properties:
                                        address:
                                          type: string
                                          description: The email address of the person or entity.
                                          nullable: true
                                        name:
                                          type: string
                                          description: The display name of the person or entity.
                                          nullable: true
                                    - type: object
                                      nullable: true
                                  description: The recipient's email address.
                            - type: object
                              nullable: true
                          description: 'The owner of the mailbox from which the message is sent. In most cases, this value is the same as the sender property, except for sharing or delegation scenarios. The value must correspond to the actual mailbox used. Find out more about setting the from and sender properties of a message.'
                        hasAttachments:
                          type: boolean
                          description: 'Indicates whether the message has attachments. This property doesn''t include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the body property to look for a src attribute, such as <IMG src=''cid:image001.jpg@01D26CD8.6C05F070''>.'
                          nullable: true
                        importance:
                          anyOf:
                            - title: importance
                              enum:
                                - low
                                - normal
                                - high
                              type: string
                            - type: object
                              nullable: true
                        inferenceClassification:
                          anyOf:
                            - title: inferenceClassificationType
                              enum:
                                - focused
                                - other
                              type: string
                            - type: object
                              nullable: true
                        internetMessageHeaders:
                          type: array
                          items:
                            title: internetMessageHeader
                            type: object
                            properties:
                              name:
                                type: string
                                description: Represents the key in a key-value pair.
                                nullable: true
                              value:
                                type: string
                                description: The value in a key-value pair.
                                nullable: true
                        internetMessageId:
                          type: string
                          nullable: true
                        isDeliveryReceiptRequested:
                          type: boolean
                          nullable: true
                        isDraft:
                          type: boolean
                          nullable: true
                        isRead:
                          type: boolean
                          nullable: true
                        isReadReceiptRequested:
                          type: boolean
                          nullable: true
                        parentFolderId:
                          type: string
                          nullable: true
                        receivedDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          format: date-time
                          nullable: true
                        replyTo:
                          type: array
                          items:
                            title: recipient
                            type: object
                            properties:
                              emailAddress:
                                anyOf:
                                  - title: emailAddress
                                    type: object
                                    properties:
                                      address:
                                        type: string
                                        description: The email address of the person or entity.
                                        nullable: true
                                      name:
                                        type: string
                                        description: The display name of the person or entity.
                                        nullable: true
                                  - type: object
                                    nullable: true
                                description: The recipient's email address.
                        sender:
                          anyOf:
                            - title: recipient
                              type: object
                              properties:
                                emailAddress:
                                  anyOf:
                                    - title: emailAddress
                                      type: object
                                      properties:
                                        address:
                                          type: string
                                          description: The email address of the person or entity.
                                          nullable: true
                                        name:
                                          type: string
                                          description: The display name of the person or entity.
                                          nullable: true
                                    - type: object
                                      nullable: true
                                  description: The recipient's email address.
                            - type: object
                              nullable: true
                        sentDateTime:
                          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                          type: string
                          format: date-time
                          nullable: true
                        subject:
                          type: string
                          nullable: true
                        toRecipients:
                          type: array
                          items:
                            title: recipient
                            type: object
                            properties:
                              emailAddress:
                                anyOf:
                                  - title: emailAddress
                                    type: object
                                    properties:
                                      address:
                                        type: string
                                        description: The email address of the person or entity.
                                        nullable: true
                                      name:
                                        type: string
                                        description: The display name of the person or entity.
                                        nullable: true
                                  - type: object
                                    nullable: true
                                description: The recipient's email address.
                        uniqueBody:
                          anyOf:
                            - title: itemBody
                              type: object
                              properties:
                                content:
                                  type: string
                                  description: The content of the item.
                                  nullable: true
                                contentType:
                                  anyOf:
                                    - title: bodyType
                                      enum:
                                        - text
                                        - html
                                      type: string
                                    - type: object
                                      nullable: true
                                  description: The type of the content. Possible values are text and html.
                            - type: object
                              nullable: true
                        webLink:
                          type: string
                          nullable: true
                        attachments:
                          type: array
                          items:
                            allOf:
                              - title: entity
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: The unique identifier for an entity. Read-only.
                              - title: attachment
                                type: object
                                properties:
                                  contentType:
                                    type: string
                                    description: The MIME type.
                                    nullable: true
                                  isInline:
                                    type: boolean
                                    description: 'true if the attachment is an inline attachment; otherwise, false.'
                                  lastModifiedDateTime:
                                    pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
                                    type: string
                                    description: 'The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z'
                                    format: date-time
                                    nullable: true
                                  name:
                                    type: string
                                    description: The attachment's file name.
                                    nullable: true
                                  size:
                                    maximum: 2147483647
                                    minimum: -2147483648
                                    type: integer
                                    description: The length of the attachment in bytes.
                                    format: int32
                          description: The fileAttachment and itemAttachment attachments for the message.
                          x-ms-navigationProperty: true
                        extensions:
                          type: array
                          items:
                            allOf:
                              - title: entity
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: The unique identifier for an entity. Read-only.
                              - title: extension
                                type: object
                          description: The collection of open extensions defined for the message. Nullable.
                          x-ms-navigationProperty: true
                        multiValueExtendedProperties:
                          type: array
                          items:
                            allOf:
                              - title: entity
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: The unique identifier for an entity. Read-only.
                              - title: multiValueLegacyExtendedProperty
                                type: object
                                properties:
                                  value:
                                    type: array
                                    items:
                                      type: string
                                      nullable: true
                                    description: A collection of property values.
                          description: The collection of multi-value extended properties defined for the message. Nullable.
                          x-ms-navigationProperty: true
                        singleValueExtendedProperties:
                          type: array
                          items:
                            allOf:
                              - title: entity
                                type: object
                                properties:
                                  id:
                                    type: string
                                    description: The unique identifier for an entity. Read-only.
                              - title: singleValueLegacyExtendedProperty
                                type: object
                                properties:
                                  value:
                                    type: string
                                    description: A property value.
                                    nullable: true
                          description: The collection of single-value extended properties defined for the message. Nullable.
                          x-ms-navigationProperty: true
                SaveToSentItems:
                  type: boolean
                  default: false
                  nullable: true
        required: true
      responses:
        '204':
          description: Success
        default:
          description: error
          content:
            application/json:
              schema:
                required:
                  - error
                type: object
                properties:
                  error:
                    required:
                      - code
                      - message
                    type: object
                    properties:
                      code:
                        type: string
                      message:
                        type: string
                        x-ms-primary-error-message: true
                      target:
                        type: string
                        nullable: true
                      details:
                        type: array
                        items:
                          required:
                            - code
                            - message
                          type: object
                          properties:
                            code:
                              type: string
                            message:
                              type: string
                            target:
                              type: string
                              nullable: true
                      innerError:
                        type: object
                        description: The structure of this object is service-specific
      x-ms-docs-operation-type: action
components: { }
```

</details>

<details>

<summary>
Expand to see original YAML section for sendMail
</summary>

```yaml
  /me/microsoft.graph.sendMail:
    description: Provides operations to call the sendMail method.
    post:
      tags:
        - me.Actions
      summary: Invoke action sendMail
      description: 'Send the message specified in the request body using either JSON or MIME format. When using JSON format, you can include a file attachment in the same sendMail action call. When using MIME format: This method saves the message in the Sent Items folder. Alternatively, create a draft message to send later. To learn more about the steps involved in the backend before a mail is delivered to recipients, see here.'
      externalDocs:
        description: Find more info here
        url: https://learn.microsoft.com/graph/api/user-sendmail?view=graph-rest-1.0
      operationId: me.sendMail
      requestBody:
        $ref: '#/components/requestBodies/sendMailRequestBody'
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
```

</details>

<details>

<summary>
Expand to see referenced sendMailRequestBody and message objects from original YAML
</summary>

```yaml
    sendMailRequestBody:
      description: Action parameters
      content:
        application/json:
          schema:
            type: object
            properties:
              Message:
                $ref: '#/components/schemas/microsoft.graph.message'
              SaveToSentItems:
                type: boolean
                default: false
                nullable: true
      required: true
```

```yaml
    microsoft.graph.message:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.outlookItem'
        - title: message
          type: object
          properties:
            bccRecipients:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.recipient'
              description: 'The Bcc: recipients for the message.'
            body:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.itemBody'
                - type: object
                  nullable: true
              description: The body of the message. It can be in HTML or text format. Find out about safe HTML in a message body.
            bodyPreview:
              type: string
              description: The first 255 characters of the message body. It is in text format.
              nullable: true
            ccRecipients:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.recipient'
              description: 'The Cc: recipients for the message.'
            conversationId:
              type: string
              description: The ID of the conversation the email belongs to.
              nullable: true
            conversationIndex:
              type: string
              description: Indicates the position of the message within the conversation.
              format: base64url
              nullable: true
            flag:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.followupFlag'
                - type: object
                  nullable: true
              description: 'The flag value that indicates the status, start date, due date, or completion date for the message.'
            from:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.recipient'
                - type: object
                  nullable: true
              description: 'The owner of the mailbox from which the message is sent. In most cases, this value is the same as the sender property, except for sharing or delegation scenarios. The value must correspond to the actual mailbox used. Find out more about setting the from and sender properties of a message.'
            hasAttachments:
              type: boolean
              description: 'Indicates whether the message has attachments. This property doesn''t include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the body property to look for a src attribute, such as <IMG src=''cid:image001.jpg@01D26CD8.6C05F070''>.'
              nullable: true
            importance:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.importance'
                - type: object
                  nullable: true
            inferenceClassification:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.inferenceClassificationType'
                - type: object
                  nullable: true
            internetMessageHeaders:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.internetMessageHeader'
            internetMessageId:
              type: string
              nullable: true
            isDeliveryReceiptRequested:
              type: boolean
              nullable: true
            isDraft:
              type: boolean
              nullable: true
            isRead:
              type: boolean
              nullable: true
            isReadReceiptRequested:
              type: boolean
              nullable: true
            parentFolderId:
              type: string
              nullable: true
            receivedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            replyTo:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.recipient'
            sender:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.recipient'
                - type: object
                  nullable: true
            sentDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            subject:
              type: string
              nullable: true
            toRecipients:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.recipient'
            uniqueBody:
              anyOf:
                - $ref: '#/components/schemas/microsoft.graph.itemBody'
                - type: object
                  nullable: true
            webLink:
              type: string
              nullable: true
            attachments:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.attachment'
              description: The fileAttachment and itemAttachment attachments for the message.
              x-ms-navigationProperty: true
            extensions:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.extension'
              description: The collection of open extensions defined for the message. Nullable.
              x-ms-navigationProperty: true
            multiValueExtendedProperties:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.multiValueLegacyExtendedProperty'
              description: The collection of multi-value extended properties defined for the message. Nullable.
              x-ms-navigationProperty: true
            singleValueExtendedProperties:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.singleValueLegacyExtendedProperty'
              description: The collection of single-value extended properties defined for the message. Nullable.
              x-ms-navigationProperty: true
```

</details>

**Comment by SergeyMenshykh** [comment]
This issue is a combination of two other issues, found here: https://github.com/microsoft/semantic-kernel/issues/6885 and https://github.com/microsoft/semantic-kernel/issues/8997. It will be resolved once those two issues are fixed.
