### ISSUE TITLE
Python: AttributeError: 'Kernel' object has no attribute 'run_async'

### ISSUE THREAD

**Issue by Jasper-zh** [microsoft/semantic-kernel#5471]
https://learn.microsoft.com/en-us/semantic-kernel/prompts/saving-prompts-as-files?tabs=python

Is the document not updated?

My version 0.9.2
```
    result = asyncio.run(kernel.run_async(
        my_plugins["city_point"],
        input_vars=["wuhan"],
    ))
    print(result)
```
Traceback (most recent call last):
  File "C:\Users\zhang\MySpace\dev\coding\python\file_exhange\semantic_kernel_02.py", line 30, in <module>
    result = asyncio.run(kernel.run_async(
                         ^^^^^^^^^^^^^^^^
  File "C:\Users\zhang\MySpace\dev\coding\python\file_exhange\.venv\Lib\site-packages\pydantic\main.py", line 761, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'Kernel' object has no attribute 'run_async'

**Comment by moonbox3** [comment]
@Jasper-zh Correct, this doc needs an update. Please refer to these [examples](https://github.com/microsoft/semantic-kernel/tree/main/python/samples/documentation_examples), or any other kernel example in the samples folder, as well as Jupyter notebooks.

`await kernel.run_async(...)` -> `await kernel.invoke(...)`

We're tracking this doc update in a separate work item, so closing this issue.
