### ISSUE TITLE
.Net: exception accured when i attempted add semantic memory as a plugin.

### ISSUE THREAD

**Issue by pangjianxin** [microsoft/semantic-kernel#5670]
**Describe the bug**
exception accured when i attempted add semantic memory as a plugin.
**To Reproduce**
i created a extension method to add semantic memory as a plugin,what i did is shown below:

`
        public static IKernelBuilder AddQdrantSemanticMemory(this IKernelBuilder builder, IConfiguration configuration)
        {
#pragma warning disable SKEXP0001, SKEXP0010, SKEXP0050,SKEXP0020 // 类型仅用于评估，在将来的更新中可能会被更改或删除。取消此诊断以继续。
            var memoryBuilder = new MemoryBuilder()
                .WithOpenAITextEmbeddingGeneration(
                     modelId: configuration["OpenAI:Chat:ModelId"]!,
                     apiKey: configuration["OpenAI:Chat:ApiKey"]!,
                     httpClient: new HttpClient(new OneApiEmbeddingHttpClientHandler(configuration)))
                .WithQdrantMemoryStore("http://localhost:6333", 1536);

            var textMemoryPlugin = new TextMemoryPlugin(memoryBuilder.Build(), null);

            KernelPlugin plugin = KernelPluginFactory.CreateFromObject(textMemoryPlugin, "SemanticMemory");

            builder.Plugins.AddFromObject(plugin);
`

**Expected behavior**
i can invoke the "SemanticMemory" plugin via Kernel,like `  await _kernel.InvokeAsync("SemanticMemory", "Save", argument);`

**Screenshots**
Autofac.Core.DependencyResolutionException: An exception was thrown while activating Castle.Proxies.AiHubProxy -> Microsoft.SemanticKernel.Kernel -> Microsoft.SemanticKernel.KernelPluginCollection -> λ:Microsoft.SemanticKernel.KernelPlugin[] -> λ:Microsoft.SemanticKernel.KernelPlugin.
 ---> System.ArgumentException: The Microsoft.SemanticKernel.DefaultKernelPlugin instance doesn't expose any public [KernelFunction]-attributed methods.
   at Microsoft.SemanticKernel.KernelPluginFactory.CreateFromObject(Object target, String pluginName, ILoggerFactory loggerFactory)
   at Microsoft.SemanticKernel.KernelExtensions.<>c__DisplayClass14_0.<AddFromObject>b__0(IServiceProvider serviceProvider)
   at Autofac.Extensions.DependencyInjection.AutofacRegistration.<>c__DisplayClass4_0.<Register>b__1(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Delegate.DelegateActivator.<ConfigurePipeline>b__2_0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.DisposalTrackingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   --- End of inner exception stack trace ---
   at Autofac.Core.Resolving.Middleware.ActivatorErrorHandlingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Builder.RegistrationBuilder`3.<>c__DisplayClass35_0.<OnPreparing>b__0(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.SharingMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.Middleware.CircularDependencyDetectorMiddleware.Execute(ResolveRequestContext context, Action`1 next)
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, ResolveRequest& request)
   at Autofac.Core.Resolving.ResolveOperation.ExecuteOperation(ResolveRequest& request)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveOptionalService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
   at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)

**Platform**
 - OS: win11
 - IDE: visual studio 2022 profetional
 - Language: C#

**Additional context**

**Comment by pangjianxin** [comment]
i made a mistake,sorry for that,this issue should be closed
