### ISSUE TITLE
Python: Unable to pass args to Planner object

### ISSUE THREAD

**Issue by akshyasingh-kuiper** [microsoft/semantic-kernel#6080]
**Describe the bug**
I have created a planner object and added plugins to kernel. These plugins need variables. Below is the json that planner created
```
{
  "plan": [
    {
      "step": 1,
      "function": "fileIQPlugin.summaryPlugin",
      "description": "Analyze the dataset to understand its structure and contents, which is essential before restructuring according to a specified schema.",
      "args": {
        "input": "Input Dataframe"
      }
    },
    {
      "step": 2,
      "function": "fileIQPlugin.transformPlugin",
      "description": "Split the analyzed input dataframe into multiple dataframes based on the specified schema, align and add missing columns as necessary, and save each as a CSV file in the provided output directory. This step directly addresses the goal of managing, restructuring, and practical application of the dataset.",
      "args": {
        "input": "Input Dataframe",
        "summary": "Summary of the input dataframe",
        "schema": "Schema to split the input dataframe",
        "output_dir": "Output Directory"
      }
    }
  ]
}
```
When I am running the below command I am getting error: 
```
    # asyncio.run(main())
    new_plan = asyncio.run(basicPlan())

    # Execute the planner
    results = asyncio.run(planner.execute_plan(new_plan, kernel))
```

ERROR: 
```
Traceback (most recent call last):
  File "/Users/akshyasingh/Documents/GitHub/file-iq-semantic/src/transform_IQ.py", line 96, in <module>
    results = asyncio.run(planner.execute_plan(new_plan, kernel))
  File "/Users/akshyasingh/anaconda3/envs/file-iq-semantic/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/akshyasingh/anaconda3/envs/file-iq-semantic/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/akshyasingh/anaconda3/envs/file-iq-semantic/lib/python3.10/site-packages/semantic_kernel/planners/basic_planner.py", line 221, in execute_plan
    arguments = KernelArguments(input=generated_plan["input"])
KeyError: 'input'
```

**Platform**
 - OS: [ Mac]
 - IDE: [Pycharm]
 - Language: [Python]
 - Source: [Semantic-kernel version 0.9.6b1]

**Additional context**
How can I run the planner?

**Comment by moonbox3** [comment]
As part of bringing the Python SDK to parity with dotnet, we have retired the Basic, Action, and Stepwise planners within the last day. Please note that we may also be making more planner changes in the future. For now, you may utilize the Sequential Planner or the Function Calling Stepwise Planner.
