### ISSUE TITLE
SK Memory Qdrant fail in Microsoft.SemanticKernel, 0.12.207.1-preview 

### ISSUE THREAD

**Issue by kinfey** [microsoft/semantic-kernel#614]
**Describe the bug**
I set SK memory to use Qdrant . In 0.11 version , it is okay . But in 0.12 version , it give me some errors like this 

when I save data in Qdrant , errors:

 Error: Microsoft.SemanticKernel.AI.AIException: InvalidRequest: The request is not valid, HTTP status: 404

at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.RunRequestAsync[T](Func`1 request)

at Microsoft.SemanticKernel.Connectors.AI.OpenAI.AzureSdk.ClientBase.InternalGenerateTextEmbeddingsAsync(IList`1 data, CancellationToken cancellationToken)

at Microsoft.SemanticKernel.AI.Embeddings.EmbeddingGenerationExtensions.GenerateEmbeddingAsync[TValue,TEmbedding](IEmbeddingGeneration`2 generator, TValue value, CancellationToken cancellationToken)

at Microsoft.SemanticKernel.Memory.SemanticTextMemory.SaveInformationAsync(String collection, String text, String id, String description, String additionalMetadata, CancellationToken cancel)

at Submission#21.<<Initialize>>d__0.MoveNext()

--- End of stack trace from previous location ---

at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)

**To Reproduce**

I save data in Qdrant,and run this script, it show me this error

await kernel.Memory.SaveInformationAsync(MemoryCollectionName, id: "id1", text: "....."); 

But when I downgrade 0.11 , everything is okay

**Comment by awharrison-28** [comment]
@tawalke FYI

**Comment by tawalke** [comment]
@kinfey Can you save the data directly to Qdrant (via curl for ex) and get a 200 back? I can also try on my end if you want to send me data to try from a Qdrant perspective. 

@awharrison-28 Thanks for the heads up. 
I don't think this is on the server aspect of Qdrant looking at the stack trace above but let's collab on troubleshooting.

**Comment by kinfey** [comment]
hi I solve now， 0.12+ connect azure openai sdk model name change ,thx

**Comment by georgian3590** [comment]
hi @kinfey i am facing the same problem after upgrading to 0.13... can you please suggest what changes you did. my code. 
![image](https://user-images.githubusercontent.com/31180068/235460501-2184fd16-183f-4efe-a635-a7e0143ab229.png)
