### ISSUE TITLE
Python: jinja2 template not working in prompt flow with semantic kernel 1.0.3

### ISSUE THREAD

**Issue by rvishwakarma001** [microsoft/semantic-kernel#6640]
**Describe the bug**
I am using semantic kernel 1.0.3 in Azure machine learning prompt flow and getting below error when using jinja2 template:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/kernel.py", line 179, in invoke
    return await function.invoke(kernel=self, arguments=arguments, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function.py", line 211, in invoke
    await stack(function_context)
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 146, in _invoke_internal
    prompt_render_result = await self._render_prompt(context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 233, in _render_prompt
    await stack(prompt_render_context)
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 245, in _inner_render_prompt
    context.rendered_prompt = await self.prompt_template.render(context.kernel, context.arguments)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/prompt_template/jinja2_prompt_template.py", line 92, in render
    {
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/prompt_template/jinja2_prompt_template.py", line 93, in <dictcomp>
    function.fully_qualified_name.replace("-", "_"): create_template_helper_from_function(
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/semantic_kernel/prompt_template/utils/template_function_helpers.py", line 31, in create_template_helper_from_function
    nest_asyncio.apply()
  File "/usr/local/lib/python3.11/site-packages/nest_asyncio.py", line 19, in apply
    _patch_loop(loop)
  File "/usr/local/lib/python3.11/site-packages/nest_asyncio.py", line 193, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
 - OS: [e.g. Windows, Mac]
 - IDE: Azure machine learning prompt flow 
 - Language: Python
 - Source: pip 24.0

**Additional context**

**Comment by alliscode** [comment]
@eavanvalkenburg would you mind taking a look at this?

**Comment by eavanvalkenburg** [comment]
@rvishwakarma001 please upgrade to 1.0.4 or later, it has upgrade jinja2 templates to use asyncio natively which does not need or use the nest_asyncio and should get you around this error! Please let us know if that helped!

**Comment by rvishwakarma001** [comment]
> @rvishwakarma001 please upgrade to 1.0.4 or later, it has upgrade jinja2 templates to use asyncio natively which does not need or use the nest_asyncio and should get you around this error! Please let us know if that helped!

@eavanvalkenburg Thanks, it's working now after updated to latest version

**Comment by eavanvalkenburg** [comment]
@rvishwakarma001 thanks for reporting back! For future reference, at time of writing, handlebars templates use nest_asyncio in order to run the kernel functions in template rendering, which means that the above error throws when using that with other async frameworks like uvloop, anyio or others. Use jinja2 or semantic-kernel templates when you want that.
