### ISSUE TITLE
Invalid value for 'content': expected a string, got null.

### ISSUE THREAD

**Issue by imranshams** [microsoft/semantic-kernel#6720]
**Describe the bug**
I'm trying to develop chat bot with Azure Open AI + Semantic-Kernel on my Apple M3 Chip and getting following exception:
`Unhandled exception rendering component: Invalid value for 'content': expected a string, got null.
      Status: 400 (Bad Request)
      
      Content:
      {
        "error": {
          "message": "Invalid value for 'content': expected a string, got null.",
          "type": "invalid_request_error",
          "param": "messages.[0].content",
          "code": null
        }
      }
      
      Headers:
      apim-request-id: REDACTED
      Content-Length: 187
      Content-Type: application/json`

My code is based on this MS [Link](https://learn.microsoft.com/en-us/azure/app-service/deploy-intelligent-apps?pivots=openai-dotnet)
`
private async Task SemanticKernelClient()
{
	// Azure OpenAI
	string deploymentName = _config["DEPLOYMENT_NAME"];
	string endpoint = _config["ENDPOINT"];
	string apiKey = _config["API_KEY"];
	string modelId = _config["MODEL_ID"];

	// Semantic Kernel client
	var builder = Kernel.CreateBuilder();
	// Azure OpenAI
	var kernel = builder.AddAzureOpenAIChatCompletion(
			deploymentName: deploymentName,
			endpoint: endpoint,
			apiKey: apiKey,
			modelId: modelId
		)
		.Build();

	var prompt = @"{{$input}} " + newQuery;

	var summarize = kernel.CreateFunctionFromPrompt(prompt, executionSettings: new OpenAIPromptExecutionSettings { MaxTokens = 100, Temperature = 0.2 });

	var result = await kernel.InvokeAsync(summarize);

	serverResponse = result.ToString();

}
`

**Platform**
 - OS: Mac OS M3 
 - IDE: Visual Studio 2022 (Running on Parallel Windows 11 Pro, 64-bit operating system, ARM-based processor)
 - Language: C#
 - Source: NuGet package version 1.14.1
 
 **Stack**
`
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid value for 'content': expected a string, got null.
      Status: 400 (Bad Request)
      
      Content:
      {
        "error": {
          "message": "Invalid value for 'content': expected a string, got null.",
          "type": "invalid_request_error",
          "param": "messages.[0].content",
          "code": null
        }
      }
      
      Headers:
      apim-request-id: REDACTED
      Content-Length: 187
      Content-Type: application/json
      
Microsoft.SemanticKernel.HttpOperationException: Invalid value for 'content': expected a string, got null.
Status: 400 (Bad Request)

Content:
{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[0].content",
    "code": null
  }
}

Headers:
apim-request-id: REDACTED
Content-Length: 187
Content-Type: application/json

 ---> Azure.RequestFailedException: Invalid value for 'content': expected a string, got null.
Status: 400 (Bad Request)

Content:
{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[0].content",
    "code": null
  }
}

Headers:
apim-request-id: REDACTED
Content-Length: 187
Content-Type: application/json

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__53`1[[Azure.Response`1[[Azure.AI.OpenAI.ChatCompletions, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.39.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<RunRequestAsync>d__53`1[[Azure.Response`1[[Azure.AI.OpenAI.ChatCompletions, Azure.AI.OpenAI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]], Azure.Core, Version=1.39.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8]].MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(ChatHistory chat, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, String prompt, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.KernelFunction.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.SemanticKernel.Kernel.InvokeFilterOrFunctionAsync(NonNullCollection`1 functionFilters, Func`2 functionCallback, FunctionInvocationContext context, Int32 index)
   at Microsoft.SemanticKernel.Kernel.OnFunctionInvocationAsync(KernelFunction function, KernelArguments arguments, FunctionResult functionResult, Func`2 functionCallback)
   at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)

`

**Comment by markwallace-microsoft** [comment]
@imranshams Is this issue still reproducible?

**Comment by imranshams** [comment]
We don't use SDK in Blazor web app anymore, we are using asp.net web app
