### ISSUE TITLE
Bug: What's Maximum return string length from Kernel_function plugin.

### ISSUE THREAD

**Issue by ossamaabdelatif2** [microsoft/semantic-kernel#6821]
**Describe the bug**
I have a plugin function that retrun string value. Observed when the string is lengthy it through error.

**semantic_kernel\contents\function_call_content.py**", line 61, in parse_arguments

    def parse_arguments(self) -> dict[str, Any] | None:
        """Parse the arguments into a dictionary."""
        if not self.arguments:
            return None
        try:
            **return json.loads(self.arguments)**
        except json.JSONDecodeError as exc:
            raise FunctionCallInvalidArgumentsException("Function Call arguments are not valid JSON.") from ex

Below shorten string works fine:
"Python is a high level, general purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage collected. It supports multiple programming paradigms, including structured (particularly procedural), object oriented and functional programming. It is often described as a batteries included language due to its comprehensive standard library. Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language and first released it in 1991 as Python 0.9.0. Python 2.0 was released in 2000. Python 3.0, released in 2008, was a major revision not completely backward compatible with earlier versions. Python 2.7.18, released in 2020, was the last release of Python 2. Python consistently ranks as one of the most popular programming languages"

but same string with extra few words through error:
"Python is a high level, general purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation. Python is dynamically typed and garbage collected. It supports multiple programming paradigms, including structured (particularly procedural), object oriented and functional programming. It is often described as a batteries included language due to its comprehensive standard library. Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language and first released it in 1991 as Python 0.9.0. Python 2.0 was released in 2000. Python 3.0, released in 2008, was a major revision not completely backward compatible with earlier versions. Python 2.7.18, released in 2020, was the last release of Python 2. Python consistently ranks as one of the most popular programming languages, **and has gained widespread use in the machine learning community."** 

Traceback (most recent call last):
  File "..\Lib\site-packages\semantic_kernel\contents\function_call_content.py", line 61, in parse_arguments
    return json.loads(self.arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "..\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Unterminated string starting at: line 2 column 13 (char 14)

The above exception was the direct cause of the following exception:

**Comment by ossamaabdelatif2** [comment]
I did work around by passing the plugin output to summarization plug-in to reduce the text.
However, I could see this issue is resolved in the newly released version 1.1.2

**Comment by ossamaabdelatif2** [comment]
Issue seems to be resolved in the new release 1.1.2 using function call planning.
