### ISSUE TITLE
.Net: Bug:  Service request failed  Status: 404 (Not Found)

### ISSUE THREAD

**Issue by xuexiaoxuan** [microsoft/semantic-kernel#8980]
**Describe the bug**
Microsoft.SemanticKernel version 1.20 has problems Version 1.19 is fine
Ollama uses the OpenAI architecture to report error 404

this is my code

using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
#pragma warning disable SKEXP0010
var builder = Kernel.CreateBuilder();
builder.AddOpenAIChatCompletion(modelId: "qwen2:latest", apiKey: null, endpoint: new Uri("http://127.0.0.1:11434"));
var kernel = builder.Build();
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();
var history = new ChatHistory();
string? userInput;
do
{
    Console.Write("User > ");
    userInput = Console.ReadLine();
    history.AddUserMessage(userInput);
    var result = await chatCompletionService.GetChatMessageContentAsync(
       history,
       // executionSettings: openAIPromptExecutionSettings,
       kernel: kernel);
    Console.WriteLine("Assistant > " + result);
    history.AddMessage(result.Role, result.Content ?? string.Empty);
} while (userInput is not null);
Console.WriteLine("Hello, World!");

**To Reproduce**
error ：
Unhandled exception. Microsoft.SemanticKernel.HttpOperationException: Service request failed.
Status: 404 (Not Found)

 ---> System.ClientModel.ClientResultException: Service request failed.
Status: 404 (Not Found)

   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
   --- End of inner exception stack trace ---
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentAsync(IChatCompletionService chatCompletionService, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\10756\source\repos\ConsoleApp1\TestLLava\Program.cs:line 16
   at Program.<Main>(String[] args)

**Expected behavior**

**Screenshots**

**Platform**
 - OS:windows11
 - IDE: vs2022
 - Language: C#
 - Source: [e.g. NuGet package version 1.20, pip package version 0.1.0, main branch of repository]

**Additional context**

**Comment by shubhamkr0077** [comment]
I'm also facing the similar issue

**Comment by RogerBarreto** [comment]
This was changed after OpenAI beta.11 version, where they are not adding `v1` in the endpoint. To solve the problem you need to add `v1` before `/chat/completions`.

This is described in the Migration Guide here
https://learn.microsoft.com/en-us/semantic-kernel/support/migration/v2-openai-migration-guide#5-openai-chatcompletion-custom-endpoint
