### ISSUE TITLE
.Net: Bug: Could not load type 'OpenAI.OpenAIClient'  after upgrading from 1.17.2 to 1.20.0

### ISSUE THREAD

**Issue by roldengarm** [microsoft/semantic-kernel#8994]
**Describe the bug**
After upgrading from 1.17.2 to 1.20.0 I get the below exception when calling kernel.InvokeAsync(). We're using Azure OpenAI.:
```
Could not load type 'OpenAI.OpenAIClient' from assembly 'OpenAI, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.
      System.TypeLoadException: Could not load type 'OpenAI.OpenAIClient' from assembly 'OpenAI, Version=8.7.1.0, Culture=neutral, PublicKeyToken=null'.
         at Microsoft.SemanticKernel.AzureOpenAIKernelBuilderExtensions.<>c__DisplayClass0_0.<AddAzureOpenAIChatCompletion>b__0(IServiceProvider serviceProvider, Object _)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetRequiredKeyedService(Type serviceType, Object serviceKey, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceProviderKeyedServiceExtensions.GetRequiredKeyedService[T](IServiceProvider provider, Object serviceKey)
         at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
         at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Boolean& found)
         at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
         at Microsoft.SemanticKernel.Services.OrderedAIServiceSelector.<TrySelectAIService>g__GetAnyService|3_0[T](Kernel kernel)
         at Microsoft.SemanticKernel.Services.OrderedAIServiceSelector.TrySelectAIService[T](Kernel kernel, KernelFunction function, KernelArguments arguments, T& service, PromptExecutionSettings& serviceSettings)
         at Microsoft.SemanticKernel.KernelFunctionFromPrompt.RenderPromptAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunctionFromPrompt.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunction.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.SemanticKernel.Kernel.InvokeFilterOrFunctionAsync(NonNullCollection`1 functionFilters, Func`2 functionCallback, FunctionInvocationContext context, Int32 index)
         at Microsoft.SemanticKernel.Kernel.OnFunctionInvocationAsync(KernelFunction function, KernelArguments arguments, FunctionResult functionResult, Func`2 functionCallback, CancellationToken cancellationToken)
         at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
```

**To Reproduce**
```
var builder = Kernel.CreateBuilder();
// deploymentName, azureEndpoint, and apiKey are variables containing the various settings.
builder.AddAzureOpenAIChatCompletion(deploymentName, azureEndpoint, apiKey);
var kernel = builder.Build();
var skPrompt =
        @"{{$input}}

Summarize the content above.";

var summaryFunction = kernelGpt4Mini.CreateFunctionFromPrompt(
  skPrompt,
  executionSettings: new OpenAIPromptExecutionSettings
  {
    MaxTokens = 1000,
    Temperature = 0.2,
    TopP = 0.5,
  }
);

var summary = await kernel.InvokeAsync(
  summaryFunction,
  new() { ["input"] = trimmedText }
);
```
**Expected behavior**
It works without errors.

**Platform**
 - OS: Windows
 - IDE: Visual Studio and VS Code
 - Language: C#
 - Source: 1.20.0 nuget

**Comment by RogerBarreto** [comment]
Observing a bit more your detailed error it says `OpenAI, Version=8.7.1.0` and AFAIK the `OpenAI` SDK version is `beta.x`, ensure you don't have a conflicting namespace called `OpenAI` by any chance, this could be the reason as now we have an official `OpenAI` namespace packages (dependencies used in `1.18+`)
