### ISSUE TITLE
.Net: Bug: Microsoft.SemanticKernel.Yaml is incompatible with current YamlDotNet, causing TypeLoadException at runtime

### ISSUE THREAD

**Issue by jphorv-bdo** [microsoft/semantic-kernel#9051]
**Describe the bug**
Using `KernelFunctionYaml.FromPromptYaml()` to deserialize YAML to an SK function in an existing codebase, with an existing dependency on `YamlDotNet` latest version (16.1.3).

The call to `KernelFunctionYaml.FromPromptYaml()` results in a `TypeLoadException` with the message:

> Method 'ReadYaml' in type 'Microsoft.SemanticKernel.PromptExecutionSettingsTypeConverter' from assembly 'Microsoft.SemanticKernel.Yaml, Version=1.20.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3' does not have an implementation.

It appears to be a breaking change with YamlDotNet 16.0.0, released 7/14/2024, specifically a change to the method signature of `IYamlTypeConverter.ReadYaml()`

**To Reproduce**
1. Have a project that references `YamlDotNet` 16.1.3 and `Microsoft.SemanticKernel.Yaml`
2. Call `KernelFunctionYaml.FromPromptYaml()` with valid (or invalid) YAML.
3. The `TypeLoadException` is thrown.

**Expected behavior**
The call to `KernelFunctionYaml.FromPromptYaml()` should parse the YAML and if it is valid, return a valid KernelFunction object.

**Screenshots**
N/A

**Platform**
 - OS: Windows
 - IDE: Visual Studio 2022
 - Language: .NET 8, C#
 - Source: YamlDotNet 16.1.3, Microsoft.SemanticKernel.Yaml 1.20.0 - 1.21.1

**Additional context**
The problem occurred while using Microsoft.SemanticKernel.Yaml < 1.20.0 but was not investigated until now.

**Comment by evchaki** [comment]
@jphorv-bdo thanks for reporting this.  @markwallace-microsoft will take a look.

**Comment by RicardoNiepel** [comment]
@markwallace-microsoft this is still open with YamlDotNet 16.3.0 and Microsoft.SemanticKernel.Yaml 1.33.0

**Comment by luismanez** [comment]
I'm having the same issue. Is there any workaround? should we downgrade the SK package? I'm not adding the YamlDotNet package explicitely, just using these packages:

```
<PackageReference Include="Microsoft.SemanticKernel" Version="1.35.0" />
<PackageReference Include="Microsoft.SemanticKernel.Yaml" Version="1.35.0" />
```

and when calling:

```
var myYaml = EmbeddedResource.Read("my.yaml");
var myFunction = _kernel.CreateFunctionFromPromptYaml(myYaml);
```

I'm getting the error:

```
Method 'ReadYaml' in type 'Microsoft.SemanticKernel.PromptExecutionSettingsTypeConverter' from assembly 'Microsoft.SemanticKernel.Yaml, Version=1.35.0.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3' does not have an implementation.
         at Microsoft.SemanticKernel.KernelFunctionYaml.ToPromptTemplateConfig(String text)
         at Microsoft.SemanticKernel.KernelFunctionYaml.FromPromptYaml(String text, IPromptTemplateFactory promptTemplateFactory, ILoggerFactory loggerFactory)
         at Microsoft.SemanticKernel.PromptYamlKernelExtensions.CreateFunctionFromPromptYaml(Kernel kernel, String text, IPromptTemplateFactory promptTemplateFactory)
```

Am I doing something wrong? seems odd that we can´t use Yaml prompts with latest SK versions...

Thanks!

**Comment by tamaw** [comment]
I was using FastEndpoints.Swagger and downgraded to [5.30.0](https://www.nuget.org/packages/FastEndpoints.Swagger/5.30.0). Looks like the specific error was made in YamlDotNet 4 months ago. You can use `dotnet nuget why yamldotnet` find the version 16.1.3 and downgrade to something >4 months ago (from writing this of course).

**Comment by 0x326** [comment]
@markwallace-microsoft Although https://github.com/microsoft/semantic-kernel/pull/12641 has been merged, I imagine this issue will re-occur when YamlDotNet v17 is released. Can we set the YamlDotNet version to be >= 16.3.0 and < 17?

**Comment by jphorv-bdo** [comment]
> [@markwallace-microsoft](https://github.com/markwallace-microsoft) Although [#12641](https://github.com/microsoft/semantic-kernel/pull/12641) has been merged, I imagine this issue will re-occur when YamlDotNet v17 is released. Can we set the YamlDotNet version to be >= 16.3.0 and < 17?

FWIW I looked at YamlDotNet for signs of WIP and don't see much activity. Unless you see something I missed, there is nothing that suggest this will happen w/ YamlDotNet v17. Version 16 just happened to have the kind of change that is incompatible - a change to a public interface method.
