### ISSUE TITLE
.Net: Bug: System.MissingMethodException in Microsoft.SemanticKernel.AzureOpenAIKernelBuilderExtensions.CreateAzureOpenAIClient during Service Initialization

### ISSUE THREAD

**Issue by MalteFries** [microsoft/semantic-kernel#9089]
Trying to get the AzureOpenAI ChatCompletion Service always results in an error. 
Am I am doing something wrong?
Right now this makes the SK completely unusable for us.

**Describe the bug**
An unhandled System.MissingMethodException occurs when attempting to initialize the Microsoft.SemanticKernel.Connectors.AzureOpenAI.AzureOpenAIChatCompletionService.

nhandled exception. System.MissingMethodException: Method not found: 'Void Azure.AI.OpenAI.AzureOpenAIClient..ctor(System.Uri, Azure.AzureKeyCredential, Azure.AI.OpenAI.AzureOpenAIClientOptions)'.
   at Microsoft.SemanticKernel.AzureOpenAIKernelBuilderExtensions.CreateAzureOpenAIClient(String endpoint, AzureKeyCredential credentials, HttpClient httpClient)
   at Microsoft.SemanticKernel.AzureOpenAIKernelBuilderExtensions.<>c__DisplayClass0_0.<AddAzureOpenAIChatCompletion>b__0(IServiceProvider serviceProvider, Object _)
   at Microsoft.Extensions.DependencyInjection.ServiceDescriptor.<>c__DisplayClass5_0.<.ctor>b__0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.SemanticKernel.Kernel.GetRequiredService[T](Object serviceKey)
   at Program.<Main>$(String[] args) in /Users/.../RiderProjects/AzureOpenAiTest/AzureOpenAiTest/Program.cs:line 24
   at Program.<Main>(String[] args)

**To Reproduce**
```
using System.ClientModel;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.ChatCompletion;
#pragma warning disable SKEXP0001

var deploymentName = "gpt-4-turbo";
var endpoint = "https://.....openai.azure.com/";
var apiKey = "....";

var kernelBuilder = Kernel.CreateBuilder();
kernelBuilder.AddAzureOpenAIChatCompletion(deploymentName, endpoint, apiKey);


var executionSettings = new PromptExecutionSettings()
{
    FunctionChoiceBehavior = FunctionChoiceBehavior.Auto()
};

kernelBuilder.Plugins.AddFromType<LightPlugin>();
Kernel kernel = kernelBuilder.Build();
var chatCompletionService = kernel.GetRequiredService<IChatCompletionService>();

var chatHistory = new ChatHistory();
StringBuilder fullAssistantContent = new();

while (true)
{
    if (chatHistory.Count == 0 || chatHistory.Last().Role != AuthorRole.Tool)
    {
        // Console.Write("\nUser: ");
        // var input = Console.ReadLine();
        // if (string.IsNullOrWhiteSpace(input))
        // {
        //     break;
        // }

        var input = "Turn the light on";
        chatHistory.AddUserMessage(input);
    }


    Console.WriteLine("Assistant: ");
    fullAssistantContent.Clear();
    var toolCallId = "";
    var toolCallName = "";
    var toolCallArguments = "";
    var content = await chatCompletionService.GetChatMessageContentsAsync(
        chatHistory,
        executionSettings,
        kernel);
    
    Console.WriteLine(content.First().Content);

    chatHistory.AddAssistantMessage(content.First().Content);

}


public class LightPlugin
{
    public string IsOn { get; set; } = "On";

#pragma warning disable CA1024 // Use properties where appropriate
    [KernelFunction]
    [Description("Gets the state of the light.")]
    public string GetState() => IsOn;
#pragma warning restore CA1024 // Use properties where appropriate

    [KernelFunction]
    [Description("Changes the state of the light.'")]
    public string ChangeState([Description("On or Off")] string newState)
    {
        this.IsOn = newState;
        var state = GetState();

        // Print the state to the console
        Console.WriteLine($"[Light is now {state}]");

        return state;
    }
}

```

**Platform**
 - OS: Mac
 - IDE: Rider
 - Language: C#
 - Source: Azure.AI.OpenAI: 2.0.0, Microsoft.SemanticKernel: 1.21.1

**Comment by RogerBarreto** [comment]
This error seems to be related to using a `OpenAI SDK` version not currently tested for SK, the latest releases of OpenAI and AzureOpenAI SDK, deprecated the usage of `AzureKeyCrendential` in favor or `System.ClientModel.ApiKeyCredential` type, which seems to be related to the issue you are having, our `main` branch already have an update for the latest changes in their package and will be available on our next release.

Closing as fixed by
- #9078

**Comment by MalteFries** [comment]
> This error seems to be related to using a `OpenAI SDK` version not currently tested for SK, the latest releases of OpenAI and AzureOpenAI SDK, deprecated the usage of `AzureKeyCrendential` in favor or `System.ClientModel.ApiKeyCredential` type, which seems to be related to the issue you are having, our `main` branch already have an update for the latest changes in their package and will be available on our next release.
> 
> Closing as fixed by
> 
> * [.Net: {Azure}OpenAI Connectors Update to 2.1.0-beta.1 #9078](https://github.com/microsoft/semantic-kernel/pull/9078)

Ok thanks for the info, when will this release happen?

**Comment by RogerBarreto** [comment]
@MalteFries, normally we do release on Tuesdays (tomorrow), keep posted, you can also check our nightly builds if that works for u.
