### ISSUE TITLE
.Net: Bug: HTTP 400 Bad Request with Structured Outputs with Azure OpenAI

### ISSUE THREAD

**Issue by r3core** [microsoft/semantic-kernel#9102]
**Describe the bug**
I get receive the following error when using structured output functionality with Azure OpenAI. This was working fine last week with streaming mode.

Model Version: 2024-08-06

```
HTTP 400 (BadRequest) response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later
```

**To Reproduce**
1. Use Semantic Kernel C# and perform a chat completion with a json_schema response format and a valid schema.

**Expected behavior**
Streamed chat completions work without any issue and produces valid JSON.

**Platform**
 - OS: MacOS and Linux
 - IDE: Rider
 - Language: C#
 - Source: Microsoft.SemanticKernel v1.21.1

**Additional context**
Stack Trace
```
System.ClientModel.ClientResultException: HTTP 400 (BadRequest)

response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later
   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.<>c__DisplayClass9_0.<<CompleteChatStreamingAsync>g__getResultAsync|0>d.MoveNext()
--- End of stack trace from previous location ---
   at OpenAI.Chat.AsyncStreamingChatCompletionUpdateCollection.AsyncStreamingChatUpdateEnumerator.CreateEventEnumeratorAsync()
   at OpenAI.Chat.AsyncStreamingChatCompletionUpdateCollection.AsyncStreamingChatUpdateEnumerator.System.Collections.Generic.IAsyncEnumerator<OpenAI.Chat.StreamingChatCompletionUpdate>.MoveNextAsync()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetStreamingChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
--- End of stack trace from previous location ---
```

**Comment by SyntaxUnknown** [comment]
We're getting this same error without using streaming...

**Comment by N-E-W-T-O-N** [comment]
@r3core 
If possible can you please provide the code as well

**Comment by N-E-W-T-O-N** [comment]
Also you are using which mode
 gpt3.5 turbo /gpt4/gpt4o

**Comment by N-E-W-T-O-N** [comment]
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/structured-outputs?tabs=python-secure#supported-models

**Comment by N-E-W-T-O-N** [comment]
```
namespace Azure.AI.OpenAI
{
  /// <summary>
  /// Defines the scenario-independent, client-level options for the Azure-specific OpenAI client.
  /// </summary>
  public class AzureOpenAIClientOptions : ClientPipelineOptions
  {
    private AzureOpenAIAudience? _authorizationAudience;
    private string _applicationId;
    private const AzureOpenAIClientOptions.ServiceVersion LatestVersion = AzureOpenAIClientOptions.ServiceVersion.V2024_07_01_Preview;

    internal string Version { get; }
```

As you can see the current latest version is 07_01 preview
.
Also mentioned in this following table

https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models?tabs=python-output#gpt-4-and-gpt-4-turbo-models

**Comment by SyntaxUnknown** [comment]
What got me here at least is this Semantic Kernel blog post which seems to indicate this is possible?

https://devblogs.microsoft.com/semantic-kernel/using-json-schema-for-structured-output-in-net-for-openai-models/

**Comment by N-E-W-T-O-N** [comment]
I tested your  example in postman & I am getting the response as expected 
![IMG_20241008_004213](https://github.com/user-attachments/assets/b4edd4fa-792e-46dd-9994-f21d63ad0f47)

**Comment by N-E-W-T-O-N** [comment]
Unable to debug the AzureClientCore correctly

**Comment by SyntaxUnknown** [comment]
That's basically what the work around is doing so we can use structured output with semantic kernel. It's swapping out the api-version in the generated URL with a new version that supports structured output. The problem is that semantic kernel is passing an older version, right?

I'm not sure how they got it to work in the blog post.

**Comment by jeffrey-m-johnson** [comment]
Also having this issue. For the same deployment, we have structured outputs working for a langchain example, but our C# semantic kernel example throws this error saying the API doesn't support it.

langchain:
```python
from langchain_openai import AzureChatOpenAI
from pydantic import BaseModel, Field
import os

class Joke(BaseModel):
    setup: str = Field(description="Setup for the joke.")
    punchline: str = Field(description="Punchline for the joke.")

model = (
    AzureChatOpenAI(model="gpt-4o", api_key="***", azure_endpoint="***", api_version="2024-09-01-preview")
    .with_structured_output(Joke)
)

joke: Joke = model.invoke("Tell me a joke")
joke.model_dump()
```

output:
```
{'setup': "Why don't skeletons fight each other?", 'punchline': "They don't have the guts."}
```

semantic kernel c#:
```c#
using System.ComponentModel;
using System.Text.Json;
using Microsoft.SemanticKernel;
using Microsoft.SemanticKernel.Connectors.OpenAI;

#pragma warning disable SKEXP0010

public class Joke
{
    [Description("Setup for the joke.")]
    public string Setup { get; set; }

    [Description("Punchline for the joke.")]
    public string Punchline { get; set; }
}

Kernel kernel = Kernel.CreateBuilder()
    .AddAzureOpenAIChatCompletion(
        deploymentName: "gpt-4o",
        apiKey: "***",
        endpoint: "***")
    .Build();

FunctionResult result = await kernel.InvokePromptAsync(
    promptTemplate: "Tell me a joke",
    arguments: new KernelArguments(new OpenAIPromptExecutionSettings
    {
        ResponseFormat = typeof(Joke),
    }));

Joke orderDetails = JsonSerializer.Deserialize<Joke>(result.ToString())!;
orderDetails
```

output:
```
Error: Microsoft.SemanticKernel.HttpOperationException: HTTP 400 (BadRequest)

response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later
---> System.ClientModel.ClientResultException: HTTP 400 (BadRequest)

response_format value as json_schema is enabled only for api versions 2024-08-01-preview and later
at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
--- End of inner exception stack trace ---
at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.RunRequestAsync[T](Func`1 request)
at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.GetChatMessageContentsAsync(String targetModel, ChatHistory chatHistory, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.KernelFunctionFromPrompt.GetChatCompletionResultAsync(IChatCompletionService chatCompletion, Kernel kernel, PromptRenderingResult promptRenderingResult, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.KernelFunctionFromPrompt.InvokeCoreAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.KernelFunction.<>c__DisplayClass21_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.SemanticKernel.Kernel.InvokeFilterOrFunctionAsync(NonNullCollection`1 functionFilters, Func`2 functionCallback, FunctionInvocationContext context, Int32 index)
at Microsoft.SemanticKernel.Kernel.OnFunctionInvocationAsync(KernelFunction function, KernelArguments arguments, FunctionResult functionResult, Func`2 functionCallback, CancellationToken cancellationToken)
at Microsoft.SemanticKernel.KernelFunction.InvokeAsync(Kernel kernel, KernelArguments arguments, CancellationToken cancellationToken)
at Submission#17.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
```

**Comment by dmytrostruk** [comment]
> I'm not sure how they got it to work in the blog post.

@SyntaxUnknown The example in a blogpost uses OpenAI connector, not Azure OpenAI connector. I will update the content in a blogpost and show how to use it with Azure OpenAI connector. Thanks for feedback!

**Comment by rnanayakkara-infotrack** [comment]
> That's basically what the work around is doing so we can use structured output with semantic kernel. It's swapping out the api-version in the generated URL with a new version that supports structured output. The problem is that semantic kernel is passing an older version, right?
> 
> I'm not sure how they got it to work in the blog post.

I managed to get it working with the solution you linked (https://www.clearpeople.com/blog/overwriting-azure-openai-api-api-version-property-using-semantic-kernel). But this feels extremely hacky and would be good if we could pass the version directly when we add Azure OpenAI Chat Completion to the kernel.

**Comment by dmytrostruk** [comment]
> But this feels extremely hacky and would be good if we could pass the version directly when we add Azure OpenAI Chat Completion to the kernel.

@rnanayakkara-infotrack This is already possible to do with latest version of Semantic Kernel which was released today: https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.22.0.

I will update Structured Outputs examples and blog post with demonstration how to use this functionality with `apiVersion` parameter soon.

Thanks for your feedback!

**Comment by grankko** [comment]
Possibly related: https://github.com/Azure/azure-sdk-for-net/issues/46579

Looks like an issue was introduced in the Azure.AI.OpenAI 2.0.0 lib.
