### ISSUE TITLE
.Net: Bug:

### ISSUE THREAD

**Issue by shreyasudupas** [microsoft/semantic-kernel#9246]
**Describe the bug**
Method not found: 'System.ClientModel.ApiKeyCredential System.ClientModel.ApiKeyCredential.op_Implicit(System.String)'.

I am trying to run this as separate server but I am unable to do this.

I have followed this video (https://www.youtube.com/watch?v=rsW2HTM6tM8) (jump to 15 min in the video) exactly step by step but I am getting this issue in your code.

**To Reproduce**
I followed this video for the setup https://www.youtube.com/watch?v=rsW2HTM6tM8
1. After running the service setup then when I run the application, I get this error
![Image](https://github.com/user-attachments/assets/1f994932-3cc7-4e48-89b5-f669f72bb193)

StackTrace: 
at Azure.AI.OpenAI.AzureOpenAIClient..ctor(Uri endpoint, AzureKeyCredential credential, AzureOpenAIClientOptions options)
   at Microsoft.KernelMemory.AI.AzureOpenAI.Internals.AzureOpenAIClientBuilder.Build(AzureOpenAIConfig config, HttpClient httpClient, ILoggerFactory loggerFactory) in C:\Users\shreyas.udupa\source\repos\kernel-memory\extensions\AzureOpenAI\Internals\AzureOpenAIClientBuilder.cs:line 51
   at Microsoft.KernelMemory.AI.AzureOpenAI.AzureOpenAITextEmbeddingGenerator..ctor(AzureOpenAIConfig config, ITextTokenizer textTokenizer, ILoggerFactory loggerFactory, HttpClient httpClient) in C:\Users\shreyas.udupa\source\repos\kernel-memory\extensions\AzureOpenAI\AzureOpenAITextEmbeddingGenerator.cs:line 45
   at Microsoft.KernelMemory.DependencyInjection.<>c__DisplayClass0_0.<AddAzureOpenAIEmbeddingGeneration>b__0(IServiceProvider serviceProvider) in C:\Users\shreyas.udupa\source\repos\kernel-memory\extensions\AzureOpenAI\DependencyInjection.cs:line 90
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.KernelMemory.Service.ServiceConfiguration.GetServiceInstance[T](IKernelMemoryBuilder builder, Action`1 addCustomService) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\ServiceConfiguration.cs:line 619
   at Microsoft.KernelMemory.Service.ServiceConfiguration.ConfigureIngestionEmbeddingGenerators(IKernelMemoryBuilder builder) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\ServiceConfiguration.cs:line 216
   at Microsoft.KernelMemory.Service.ServiceConfiguration.BuildUsingConfiguration(IKernelMemoryBuilder builder) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\ServiceConfiguration.cs:line 97
   at Microsoft.KernelMemory.Service.ServiceConfiguration.PrepareBuilder(IKernelMemoryBuilder builder) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\ServiceConfiguration.cs:line 65
   at Microsoft.KernelMemory.KernelMemoryBuilderExtensions.FromAppSettings(IKernelMemoryBuilder builder, String settingsDirectory) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\KernelMemoryBuilderExtensions.cs:line 26
   at Microsoft.KernelMemory.Service.Program.<>c__DisplayClass1_0.<Main>b__0(IKernelMemoryBuilder memoryBuilder) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\Program.cs:line 87
   at Microsoft.KernelMemory.WebApplicationBuilderExtensions.AddKernelMemory(WebApplicationBuilder appBuilder, Action`1 configureMemoryBuilder, Action`1 configureMemory) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service.AspNetCore\WebApplicationBuilderExtensions.cs:line 31
   at Microsoft.KernelMemory.Service.Program.Main(String[] args) in C:\Users\shreyas.udupa\source\repos\kernel-memory\service\Service\Program.cs:line 85

**Expected behavior**

**Screenshots**

**Platform**
 - OS: Windows 11
 - IDE: Visual Studio 2022 Version 17.11.3
 - Language: C#
 - Source: repository as of 14 October 2024

**Additional context**

**Comment by RogerBarreto** [comment]
Ensure you are using the latest version of semantic kernel and the packages with the expected OpenAI or Azure OpenAi.

For example our latest 1.22 release packages should be used with OpenAi 2.1-beta1 as well as with Azure.AI.OpenAi 2.1-beta1

**Comment by markwallace-microsoft** [comment]
@shreyasudupas Kernel memory is a seperate project, can you create this issue here https://github.com/microsoft/kernel-memory/issues
