### ISSUE TITLE
.Net: Bug: Possible regression on function calling in a streaming scenario

### ISSUE THREAD

**Issue by rcoccia** [microsoft/semantic-kernel#9303]
I’m moving different projects from oldest version of SK to the newest 1.22.
Most of these projects are an early implementation of an agent solution based on a KernelFuction running on a Kernel with some plugins and an execution settings with an automatic function calling.

When functions execute with the InvokeAsync method everything works correctly.
When functions executes in streaming mode with the InvokeStreamingAsync, I receive an exception when the model ask for the execution of a function.

The exception is: Value cannot be null. (Parameter 'bytes')
The stack Trace is:
```c#
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount)
   at System.BinaryData.ToString()
   at Microsoft.SemanticKernel.Connectors.OpenAI.OpenAIFunctionToolCall.TrackStreamingToolingUpdate(IReadOnlyList`1 updates, Dictionary`2& toolCallIdsByIndex, Dictionary`2& functionNamesByIndex, Dictionary`2& functionArgumentBuildersByIndex)
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__16.MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__16.MoveNext()
   at Microsoft.SemanticKernel.Connectors.OpenAI.ClientCore.<GetStreamingChatMessageContentsAsync>d__16.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Microsoft.SemanticKernel.Agents.ChatCompletionAgent.<InvokeStreamingAsync>d__3.MoveNext()
   at Microsoft.SemanticKernel.Agents.ChatCompletionAgent.<InvokeStreamingAsync>d__3.MoveNext()
   at Microsoft.SemanticKernel.Agents.ChatCompletionAgent.<InvokeStreamingAsync>d__3.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
```

I’ve decide to start a new project from scratch using some of the sample and using the new agent framework

```c#
public class MenuAgent : IAgent
 {
     readonly Kernel _kernel;

     public MenuAgent(Kernel kernel)
     {
         ArgumentNullException.ThrowIfNull(kernel, nameof(kernel));
         _kernel = kernel;
         _kernel.Plugins.AddFromType<MenuPlugin>();
     }

     public async IAsyncEnumerable<string> RunAsync(Conversation conversation, CancellationToken cancellationToken)
     {

         ChatHistory chat = conversation.Messages;

         var _agent = new ChatCompletionAgent()
         {
             Kernel = _kernel,
             Instructions= "Answer questions about the menu.",
             Arguments = new KernelArguments(
                 new AzureOpenAIPromptExecutionSettings() { FunctionChoiceBehavior = FunctionChoiceBehavior.Auto() }
             )
         };

         // IT'S NOT WORKING
         await foreach (StreamingChatMessageContent response in _agent.InvokeStreamingAsync(chat, cancellationToken: cancellationToken).ConfigureAwait(false))
         {
             if (string.IsNullOrEmpty(response.Content)) { continue; }
             yield return response.Content;

         }

         // IT'S WORKING
         //await foreach (ChatMessageContent response in _agent.InvokeAsync(chat, cancellationToken: cancellationToken).ConfigureAwait(false))
         //{
         //    if (string.IsNullOrEmpty(response.Content)) { continue; }
         //    yield return response.Content;
         //}

     }
 }
``` 

But the error is still the same.
I’m currently using a gpt4-o model in Sweden.
Any idea?

**Comment by rcoccia** [comment]
Thank you very much

**Comment by rcoccia** [comment]
Hi, just updated to SK 1.24 (.Net: Fix: Enhance Function Argument Validation to Prevent Null Argument Exceptions in Tool Calls. #9273 should be present in 1.23) but the error seems still present
