### ISSUE TITLE
.Net: Bug: Crash in OnnxRuntimeGenAIChatCompletionService

### ISSUE THREAD

**Issue by lilhoser** [microsoft/semantic-kernel#9709]
**Describe the bug**
Application crashes with "bad allocation" nebulous message when iterating over vector search results:

```
var searchResult = await collection.VectorizedSearchAsync(searchVector, searchOptions);
await foreach (var item in searchResult.Results)
{
    return item.Record.Description;
}
return string.Empty;
```

Call stack:

```
   at Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(IntPtr nativeResult)
   at Microsoft.ML.OnnxRuntimeGenAI.Generator..ctor(Model model, GeneratorParams generatorParams)
   at Microsoft.SemanticKernel.Connectors.Onnx.OnnxRuntimeGenAIChatCompletionService.<RunInferenceAsync>d__13.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/Connectors/Connectors.Onnx/OnnxRuntimeGenAIChatCompletionService.cs:line 99
   at Microsoft.SemanticKernel.Connectors.Onnx.OnnxRuntimeGenAIChatCompletionService.<RunInferenceAsync>d__13.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Microsoft.SemanticKernel.Connectors.Onnx.OnnxRuntimeGenAIChatCompletionService.<GetStreamingChatMessageContentsAsync>d__12.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/Connectors/Connectors.Onnx/OnnxRuntimeGenAIChatCompletionService.cs:line 82
   at Microsoft.SemanticKernel.Connectors.Onnx.OnnxRuntimeGenAIChatCompletionService.<GetStreamingChatMessageContentsAsync>d__12.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/Connectors/Connectors.Onnx/OnnxRuntimeGenAIChatCompletionService.cs:line 82
   at Microsoft.SemanticKernel.Connectors.Onnx.OnnxRuntimeGenAIChatCompletionService.<GetStreamingChatMessageContentsAsync>d__12.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeStreamingCoreAsync>d__7`1.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs:line 304
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeStreamingCoreAsync>d__7`1.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/SemanticKernel.Core/Functions/KernelFunctionFromPrompt.cs:line 304
   at Microsoft.SemanticKernel.KernelFunctionFromPrompt.<InvokeStreamingCoreAsync>d__7`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Microsoft.SemanticKernel.KernelFunction.<InvokeStreamingAsync>d__30`1.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs:line 418
   at Microsoft.SemanticKernel.KernelFunction.<InvokeStreamingAsync>d__30`1.MoveNext() in /home/vsts/work/1/s/semantic-kernel/dotnet/src/SemanticKernel.Abstractions/Functions/KernelFunction.cs:line 430
   at Microsoft.SemanticKernel.KernelFunction.<InvokeStreamingAsync>d__30`1.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
```

![Image](https://github.com/user-attachments/assets/a11d1322-4cff-4797-ae94-aeaf794a2954)

Repro steps might be a little complicated because the data set is large.

**Comment by f2bo** [comment]
I don't know is your issue is the same, but my experience of the "bad allocation" error message with ONNX is when failing to specify `MaxTokens` in the `OnnxRuntimeGenAIPromptExecutionSettings`. If the model you are using supports a large context length, (e.g. 128K), it will attempt to allocate too much memory and fail.

I reported the issue about the "nebulous message" in the ONNX runtime genai repo (https://github.com/microsoft/onnxruntime-genai/issues/980). There's a PR in progress that makes the message slightly less obscure.

**Comment by lilhoser** [comment]
Thanks for the lead @f2bo !  If I'm reading your bug report correctly, the buffer size in this scenario (with 128k context) is ~393MB (1 * 32 *  128,000 *  96). Is that correct? Not sure why this would cause an issue on my system.

**Comment by f2bo** [comment]
Hi @lilhoser,

I'm unclear whether the allocated buffer size is calculated this way or if one of those numbers represent units that need to be multiplied by some other factor.

However, I develop in a VM to which I have currently assigned 48GB and when using a model with a large context, I always get a "bad allocation" error unless I limit the `MaxTokens` settings. For example, using `Phi-3-mini-128k-instruct-onnx` with the following code:

``` C#
var chat = new OnnxRuntimeGenAIChatCompletionService(
    modelId: "phi3.0", 
    modelPath: "... PATH TO YOUR MODEL...");
ChatHistory history = new();
history.AddUserMessage("Hi");
OnnxRuntimeGenAIPromptExecutionSettings executionSettings = new() { /*MaxTokens = 75000*/ };
await foreach (var content in chat.GetStreamingChatMessageContentsAsync(history, executionSettings))
{
    Console.Write(content);
}
```
Any `MaxTokens` setting larger than approximately 75000 or not setting a value, which by default will use the entire 128K, fails to run in my environment. The top of the call stack, after the exception, is the same as yours, which shows it occurs when constructing the Generator.
```
   at Microsoft.ML.OnnxRuntimeGenAI.Result.VerifySuccess(IntPtr nativeResult)
   at Microsoft.ML.OnnxRuntimeGenAI.Generator..ctor(Model model, GeneratorParams generatorParams)
...more
```

**Comment by RogerBarreto** [comment]
@lilhoser Just to add as my own experience dealing with the ONNX Runtime GenAI, I once had this **Bad Allocation error** when my OS Disk was running low on memory, any attempt to run the model in a low disk memory environment was triggering it.

As also @f2bo mentioned, I'm closing this issue as it is not specific Semantic Kernel and is being currently worked on ONNX repo. If the max tokens does not solve your problem suggest opening a new issue with your reproduction scenario

- https://github.com/microsoft/onnxruntime-genai/issues/980
