### ISSUE TITLE
SemanticKernel package was not working in Winforms .NetFramework.

### ISSUE THREAD

**Issue by ChidanandMurugaiah** [microsoft/semantic-kernel#9755]
**Describe the bug**

We are utilizing the Microsoft.SemanticKernel package in a .NET Framework 4.8 Winforms sample to retrieve responses from ChatGPT. However, when invoking kernel.GetRequiredService<IChatCompletionService>(), it consistently returns null. As a result, we are unable to use the ChatCompletionService to fetch AI responses. Notably, the same code functions correctly in a .NET80 environment.

**To Reproduce**
1. Run the sample
2. Click Initialize button

**Expected behavior**
Sample needs to be run properly without exception.

**Screenshots**
![Image](https://github.com/user-attachments/assets/97cd07e3-0683-4de5-bfe2-93326dabe3d8)

**Sample Link** - [SemanticKernel.zip](https://github.com/user-attachments/files/17814522/SemanticKernel.zip)

**Platform**
 - OS:Windows 11
 - IDE: VS2022 version 17.12.0
 - Language: C#
 - Source:Microsoft.SemanticKernel package version 1.21.1

**Additional context**
We saw that this package was compatible for WPF .NetFramework.

**Comment by RogerBarreto** [comment]
@ChidanandMurugaiah, can you check if this works with our latest version? 1.29 

Please provide more details about the stack trace you getting.

We had a bug 2 weeks ago related to Null reference exception when using function calling and can be related to your example

- https://github.com/microsoft/semantic-kernel/issues/9313

**Comment by ChidanandMurugaiah** [comment]
@RogerBarreto, 

**1)** can you check if this works with our latest version? 1.29

* When we try to install the latest version of the KS package we are facing the below issue.
![Image](https://github.com/user-attachments/assets/a03141ae-7b54-4da5-a30e-1ff1bacbceed)

-------

**2)** Please provide more details about the stack trace you getting.

**Below is the Stack trace**

 at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.GetChatMessageContentsAsync(IChatCompletionService chatCompletionService, String prompt, PromptExecutionSettings executionSettings, Kernel kernel, CancellationToken cancellationToken)
   at Microsoft.SemanticKernel.ChatCompletion.ChatCompletionServiceExtensions.<GetChatMessageContentAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SemanticKernel.AIService.<NonStreamingChat>d__10.MoveNext() in D:\Samples\Winforms\SemanticKernel\Form1.cs:line 57 

-------
**3)** We had a bug 1 month ago related to Null reference exception when using function calling and can be related to your example

https://github.com/microsoft/semantic-kernel/issues/9313
* We referred the query you mentioned but it was not similar to our problem. The same code works in .Net80 sample but not works in .NetFramework sample.

**Comment by RogerBarreto** [comment]
@ChidanandMurugaiah Thanks for the added context.

On the first I could not replicate your issue, all the packages were installed without a problem, maybe suggest clearing any caches or a clean build.

![Image](https://github.com/user-attachments/assets/7cf57657-8720-4cea-a08a-7de8c4b658cb)

For the error to ensure is not related to the #9313, please make sure you are using a reference to `System.Memory.Data` forcing it to use >= 8.0.0 version.

**Comment by ChidanandMurugaiah** [comment]
@RogerBarreto, Now, I am able to install the latest version of Microsoft.SemanticKernal package but for that I need to install the below packages alone.

* `Microsoft.Extensions.VectorData.Abstractions`
* `Azure.AI.OpenAI`
* `Microsoft.Extensions.AI.Abstractions`

Because these packages are in pre-release. So, when installing the SK package, these package not installed automatically in .NetFramework


Let me come to the point, even after installing the latest version of the SK, the issue still occurs.
